module.exports = {
  // Discord Emoji List
  // https://emzi0767.gl-pages.emzi0767.dev/discord-emoji/discordEmojiMap-canary.json
  makerUserId:"358320066770501632",
  discordEmbedLengthLimit: 10,
  contentsName: "内容", // Name of field
  contentsNameSelection: "\uD83D\uDD33",
  contentsNameDeselection: "▫️",

  displayAll: "都",
  displayNone: "没有一个",
  displayTotal: "总数",
  displayGrandTotal: "总计",
  displayAverageShorthand: "平均.",
  displayOtherItems: "其他",
  displayBannerName: {
    "Character Event Banner": "角色活动祈愿",
    "Weapon Event Banner": "武器活动祈愿",
    "Permanent Banner": "常驻祈愿",
    "Novice Banner": "新手祈愿",
  },
  displayItemType: {
    "Character": "角色",
    "Weapon": "武器",
  },
  
  rarity5StarEmoji: "⋆⋆⋆⋆⋆",
  rarity5StarName: "五星",
  rarity4StarEmoji: "⋆⋆⋆⋆",
  rarity4StarName: "四星",
  rarity3StarEmoji: "⋆⋆⋆",
  rarity3StarName: "三星",
  refreshName: "刷新", 
  refreshEmoji: "🔄",
  statusSuccessName: "成功",
  statusSuccessEmoji: "✅",
  statusErrorName: "错误",
  statusErrorEmoji: "❌",
  statusLoadingName: "加载着",
  statusLoadingEmoji: "📂",
  statusCheckingName: "检查着",
  statusCheckingEmoji: "⏳",
  statusProcessingName: "数据处理。。。",
  statusProcessingEmoji: "⏳",
  statusLoadedEmoji: "✅",
  statusLoadedName: "已加载",
  statusLoadingEmoji: "⏳",
  statusLoadingName: "正在加载",
  statusLoadEmoji: "❌",
  statusLoadName: "没加载",

  urlImageError: "https://cdn.discordapp.com/attachments/814486266618970162/940599883658842122/error_1.png",
  urlImage5Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801560898850907/Final_5_Star.png",
  urlImage4Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801559669923940/Final_4_Star.png",
  urlImageTally: "https://cdn.discordapp.com/attachments/814486266618970162/859426718754275399/Wish-Tally---Community.png",
  urlExportConvertor: "https://docs.google.com/spreadsheets/d/1lXGo_pKxKmTzd9pg1b1gr6Fa-zfcM2ZQd0EnFfzg8Dk/edit",
  urlDiscordInvite: "https://discord.gg/CKuJSbtndV",
  urlGoogleWishTallyAddon: "https://workspace.google.com/marketplace/app/wish_tally/791037722195",
  urlGoogleSheet: "https://docs.google.com/spreadsheets/u/0/",
  // output message
  replaceCodeURL: "[URL]",
  replaceCodeTitle: "[TITLE]",
  replaceCodeProjectName: "[PROJECT_NAME]",
  replaceCodeFileType: "[FILE_TYPE]",
  replaceCodeStatus: "[STATUS]",
  replaceCodeRank: "[RANK]",
  replaceCodeCommandName: "[COMMAND_NAME]",
  replaceCodeEmoji: "[EMOJI]",
  replaceCodeStatusEmoji: "[EMOJI_STATUS]",
  replaceCodeAccountId: "[ACCOUNT_ID]",
  replaceCodeAccountsMax: "[ACCOUNTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeCommandDescription: "[COMMAND_DESCRIPTION]",
  replaceCodeLanguage: "[LANGUAGE]",
  replaceCodeParameter: "[PARAMETER]",
  replaceCodeDate: "[DATE]",
  replaceCodeDocumentVersion: "[DOCUMENT_VERSION]",
  replaceCodeGenshinVersion: "[GENSHIN_VERSION]",
  replaceCodeAttemptIndex: "[ATTEMPTS_INDEX]",
  replaceCodeAttemptMax: "[ATTEMPTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeValue:"[VALUE]",
  replaceCodePercentage:"[PERCENTAGE]",
  outputContent: "[COMMAND_NAME]|[EMOJI_STATUS]|For <@[USER_ID]> |[LANGUAGE]|[PARAMETER]|[COMMAND_DESCRIPTION] [DATE]",

  latestVersionCustomId: "[LOAD_LATEST_VERSION]",
  latestVersionName: "最近版",
  latestVersionEmoji: "🔎",
  latestVersionTitle: "[EMOJI] Genshin Impact V版 [GENSHIN_VERSION]",
  // ping Command
  replaceCodeBotName: "[BOT_NAME]",
  pingMessage: ":wave: [BOT_NAME] 我还活着",
  // last-update Command
  lastUpdateMessageError: "请等代社区缓存标价在，状态： [STATUS]",
  lastUpdateMessageException: "错误。 无法从社区缓存加载数据: [STATUS]",
  lastUpdateName: "最近更新",
  lastUpdateTitle: "社区文档上次更新摘要",
  lastUpdateEmoji: "⏲️",
  lastUpdateCustomId: "[LOAD_LAST_UPDATE]",
  lastUpdateDocumentTitle: "社区V[DOCUMENT_VERSION]版.X",

  lastUpdateStatusCommunityAccounts: "社区账户文件",
  lastUpdateStatusLanguagePadding: 18,
  lastUpdateStatusDocumentPadding: 16,
  lastUpdateStatusDocument: "已加载文档",
  lastUpdateStatusDocumentAccount: "刷新账户",
  lastUpdateStatusDocumentCache: "刷新缓存",
  lastUpdateStatusDocumentWishes: "刷新旗帜",
  lastUpdateStatusCommunityPadding: 15,
  lastUpdateStatusItemsByBanner: "旗帜上的项目",
  lastUpdateStatusAccounts: "账户",
  lastUpdateStatusCharacterBannerPity: "保底",
  lastUpdateStatusDatePadding: 5,
  lastUpdateStatusStartDate: "开始",
  lastUpdateStatusEndDate: "结束",
  lastUpdateStatusSummaryPadding: 14,
  lastUpdateStatusDuration: "时长",
  lastUpdateStatusAttempts: "尝试",
  lastUpdateStatusMaxAccounts: "最多账户",
  lastUpdateStatusTotalWishes: "总愿望",
  lastUpdateStatusCurrentUpdates: "检查账户",
  lastUpdateStatusHour: "小时",
  lastUpdateStatusHours: "小时",
  lastUpdateStatusAnd: "和",
  lastUpdateStatusMinute: "分钟",
  lastUpdateStatusMinutes: "分钟",
  lastUpdateStatusAgo: "以前",
  /*
   * account Command
   */
  accountEmoji: "🔑",
  accountCustomId: "[LOAD_ACCOUNT]",
  accountName: "账户",
  accountTitle: "[EMOJI] 账户",
  accountDescriptionFound: "感谢您对Wish Tally社区贡献, 目前有[ACCOUNTS_MAX]个账户的数据.\n\n这里是您专属的选项。",
  accountDescriptionNotFound: "抱歉，我们找不到您的Wish Tally账户, 有 [ACCOUNTS_MAX] 个账户可用，但没有一个与您的Discord账户向关系。\n\n请访问帮助页面了解如何为Wish Tally社区作出贡献。\n\n如果您最近在ModMail上共享您的账户，则必须等待工作人员检查您的文档。",
  accountDescriptionNotLoadedAccount: "Bot最近清楚了缓存，它将很快刷新账户。目前按钮都已启用，但这些命令仍需要连接到您的Wish Tally账户。",
  accountDescriptionLayout: "\n> [EMOJI][COMMAND_NAME] - [COMMAND_DESCRIPTION]",
  accountDescriptionRank: "显示您在每个社区文档之间的总愿望，并显示您的平均保底等级。",
  accountDescriptionWish: "按等级显示您的愿望贡献，有助于了解哪个Genshin版本在社区中受欢迎。",
  accountDescriptionPity: "从您的文档中提取您最近的保底，无需截屏即可向人们展示您的愿望。",
  accountDescriptionRate: "在“角色活动旗帜”中显示限时角色的所有胜率。",
  /*
   * rank Command
   */
  rankEmoji: "🏆",
  rankCommunityEmoji: "🌎",
  rankCustomId: "[LOAD_RANK]",
  rankName: "职级",
  rankAccountTitle: "账户汇总",
  rankTitle: "职级汇总",
  rankDescription: "个人职级是您使用Wish Tally文档中的数据进行的职级。 社区职级是所有账户的平均值，这意味着您的职级越低越好。 ",
  rankCommunityTitle: "[EMOJI] 社区职级",
  rankPersonalTitle: "[EMOJI] 个人职级",
  rankNoWishes: "在这个版本中没有任何愿望。",
  /*
   * rank-wish Command
   */
  rankWishEmoji: "✨",
  rankWishCustomId: "[LOAD_RANK_WISH]",
  rankWishName: "愿望",
  rankWishLimit: 15,
  rankWishGenshinVersionLimit: 5,
  rankWishGenshinVersionSameLimit: 2,
  rankWishLimitPadding: 2,
  rankWishSameTotalLimit: 3,
  rankWishSameTotalMessage: "__阴 [STATUS] 职级__的账户 [RANK]__",
  rankWishTitle: "愿望职级",
  rankWishNotReadyMessage: "愿望账户数据尚未加载，请再试",
  rankWishLoadedMessage: "按愿望职级已成功加载",
  rankWishYouEmoji: "👈",
  rankWishRarity4StarEmoji: "4⭐",
  rankWishRarity5StarEmoji: "5⭐",
  rankWishSelectVersionDefaultPlaceholderForAll: "所有社区数据",
  rankWishRankTitle: "Wish Tally社区V版",
  rankWishRankGenshinTitle: "愿神V版",
  rankWishDocumentTitle: "Wish Tally社区V[DOCUMENT_VERSION]版.X",
  rankWishSelectVersionAllId: "[SELECT_RANK_WISH_VERSION_ALL]",
  rankWishSelectBannerIndexId: "[SELECT_RANK_WISH_BANNER_INDEX]",
  rankWishSelectVersionIndexId: "[SELECT_RANK_WISH_VERSION_INDEX]",
  rankWishMessageSuccessSelect: "在旗帜之间导航",
  rankWishMessageError: "遇到错误, 再试一次",

  checkCommunityAccountMessageError: "请等待社区账户表加载, 状态: [STATUS]",
  // finding account only show for error
  findingAccountName: "寻找账户",
  findingAccountEmoji: "🔎",
  findingAccountMessageNotFound: "错误！无法从社区账户中找到您的账户详细信息\n如果您尚未加入社区请转到帮助页面了解如何共享您的Wish Tally文档，如果您最近有青灯社区更新。",
  findingAccountMessageException: "错误! 无法从社区文档中提取数据 `[DOCUMENT_VERSION]`版.",
  findingAccountMessageError: "错误无法找到社区账户表",

  displayRankMessageError: "错误无法找到社区文档 `[DOCUMENT_VERSION]`版.",
  displayRankMessageNotFound: "社区文档 `[DOCUMENT_VERSION]`版, 还没有您的账户详细信息. 您的账户位置为 [ACCOUNT_ID]， 而有 [ACCOUNTS_MAX] 个账户可用，请等待社区更新。",
  displayRankMessageException: "错误！无法从社区中提取数据 ",
  /*
   * pity Command
   */
  pityEmoji: "🧮",
  pityCustomId: "[LOAD_PITY]",
  pityName: "保底",
  pityMessageError: "加载文档时错误",
  pityMessageLoading: "加载文档 [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] 个尝试。",
  pityMessageUnableLoad: "错误无法加载您的文档，请稍后再试。",
  pityMessageUnableFind: "错误无法从文档中找到“检查器保底” 表。",
  pityMessageLoadingPity: "加载“检查器保底”表数据 [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] 个尝试。",
  pityMessageUnablePityExtract: "从“检查器保底”表中提取错误完全失败，稍后再试。",
  pityMessagePitySheetOld: "您的文档“检查器保底”表已过期，请检查 <#836651770100842576>.",
  pityMessagePitySheetSuccess: "从您的文件表现出保底",
  pityCurrentWishNumber: "当前的第__个愿望",
  pityBackCustomId: "[LOAD_PITY_BACK]",
  pityNextCustomId: "[LOAD_PITY_NEXT]",
  pityBackEmoji: "⭐", // Back
  pityBackTitle: "⭐⭐⭐⭐⭐", // Back
  pityBackNoEarned: "⭐⭐⭐⭐⭐ - 未找到五星", // Back
  pityBackName: "五星", // Back
  pityNextEmoji: "⭐", // Next
  pityNextTitle: "⭐⭐⭐⭐", // Next
  pityNextNoEarned: "⭐⭐⭐⭐ - 未找到四星", // Next
  pityNextName: "四星", // Next
  /*
   * rate Command
   */
  rateEmoji: "🎯",
  rateCustomId: "[LOAD_RATE]",
  rateVersionCustomId: "[LOAD_RATE_VERSION]",
  rateName: "速度",
  rateTitle: "[EMOJI] 速度",
  rateDescriptionSelection: "**Key**\n👎 - 无法获得评级任务\n✌️ - 赢得50/50\n👍 - 用以前的保底赚来的\n🙌 - 在当前旗帜上使用了保底\n~~选择您希望更详细地查看的文档版本~~ 很快。",
  rateMessageError: "加载角色旗帜时遇到错误，请再试一次",
  rateNotReadyMessage: "人物旗帜保底仍在加载中，请再试。\n[STATUS]",
  rateLoadedMessage: "速度已成功加载",
  rateMenuSelectDocumentVersionPlaceholder: "选择Wish Tally社区数据",
  rateMenuSelectDocumentVersionCustomId: "[SELECT_RATE_MENU_VERSION]",
  rateMenuSelectDocumentVersionSelection: "Wish Tally社区V[DOCUMENT_VERSION]版.X",
  rateBannerDisplayLayout: "\n**[GENSHIN_VERSION]版**",
  rateInnerBannerDisplayLayout: "\n__[TITLE]__",
  rateItemDisplayLayout: "\n> [TITLE]",
  rateFirstBanner: "第一个旗帜",
  rateSecondBanner: "第二个旗帜",
  rateThirdBanner: "第三个旗帜",
  rateFourthBanner: "第四个旗帜",
  rateFifthBanner: "第五个旗帜",
  rateEmptyTotal: "没有赚到",
  rateTotalTitle: "一共",
  rateResultLayout: "`[TITLE] [VALUE]`",
  rateTotalMaxPadding: 4,
  ratePercentageMaxPadding: 3,
  rateWinEmoji: "✅",
  rateWinName: "", // Not in use
  rateLoseEmoji: "❌",
  rateLoseName: "", // Not in use

  rateFailedToGetEmoji: "👎",
  rateFailedToGetName: "失败的",
  rateFailedToGetDetailed: "无法获得评级人物",
  rateWonFiftyFiftyEmoji:"✌️",
  rateWonFiftyFiftyName:"赢得50/50",
  rateWonFiftyFiftyDetailed:"赢得50/50",
  rateUsedPityEmoji: "👍",
  rateUsedPityName: "用过的保底",
  rateUsedPityDetailed: "用以前的保底赚来的",
  rateSkippedEmoji: "👉", // Not in use
  rateSkippedName: "跳", // Not in use
  rateSkippedDetailed: "没有五星尝试",
  rateSecondAttemptEmoji: "🙌",
  rateSecondAttemptName: "使用当前的保底",
  rateSecondAttemptDetailed: "在当前旗帜上使用了保底",
  rateResultLeftPercentageLayout: "`[EMOJI][VALUE]|[PERCENTAGE]%`",
  rateResultCenterPercentageLayout: "▰",
  rateResultRightPercentageLayout: "`%[PERCENTAGE]|[VALUE][EMOJI]`",
  rateResultPercentageCovered: "▰",
  rateResultPercentageUncovered: "▱",

  languageSelectByNameCustomId: "[SELECT_LANGUAGE_NAME]",
  /*
   * tally Command
   */
  tallyEmoji: "\uD83E\uDEA7",
  tallyCustomId: "[LOAD_TALLY]",
  botEmoji: "<:wish_tally:1015215165500825611>",
  tallyName: "功能表",
  tallyTitle: "[EMOJI] Wish Tally Bot",
  tallyDescription: "**[EMOJI] 欢迎来Wish Tally选单**\n__Bot安名称管理<@[USER_ID]>__",
  tallyDescriptionBot: "使用下面的按钮来控制 [EMOJI] Wish Tally bot.",
  tallyDescriptionHelp: "此处仅显示来自Wish Tally社区的数据，请查看 [EMOJI] 帮助页面已参与。 \n\n**请注意** __只有请求bot的人才能控制bot__。",
  /*
   * report-m[DOCUMENT VERSION] Back Command
   */
  reportDocumentEmoji: "\uD83D\uDCD4",
  reportDocumentCustomId: "[LOAD_COMMUNITY_VERSION]",
  reportDocumentName: "文档",
  /*
   * report-m Command Load all doc
   */
  reportMenuEmoji: "<:wish_tally_community:1015216582231871611>",
  reportMenuCustomId: "[LOAD_COMMUNITY]",
  reportMenuName: "社区",
  reportMenuResetCustomId: "[LOAD_COMMUNITY_RESET]",
  reportMenuResetEmoji: "🗑️",
  reportMenuResetName: "重置过滤器",
  reportMenuMessageError: "无法加载版本 ’[DOCUMENT_VERSION]‘ 的社区文档可能还不存在？",
  reportMenuMessageErrorLoading: "版本 ’[DOCUMENT_VERSION]‘ 的社区文档尚未加载。",
  reportMenuMessageException: "遇到错误无法加载报告社区文档版本 `[DOCUMENT_VERSION]`, 请再试一遍？",
  reportMenuMessageNoData: "没有数据可显示用于加载社区文档版本 `[DOCUMENT_VERSION]`, 请再试一遍？",
  reportMenuMessageFound: "显示社区文档版本 `[DOCUMENT_VERSION]`",
  reportMenuDefaultPlaceholderForAll: "所有社区数据",
  reportMenuSelectCustomId: "[SELECT_REPORT_MENU_VERSION]",
  reportMenuSelectAllId: "[SELECT_REPORT_MENU_ALL]",
  reportMenuSelectGensionVersionCustomId: "[SELECT_GENSHIN_VERSION]",
  reportMenuSelectGenshinVersionPlaceholder: "选择Genshin Impact版本",
  reportMenuSelectGensionVersionName: "Genshin Impact V[GENSHIN_VERSION]版",
  reportMenuSelectIndexCustomId: "[SELECT_REPORT_MENU_INDEX]",
  reportMenuDocumentTitle: "Wish Tally社区V[DOCUMENT_VERSION]版.X",
  reportMenuDocumentSelectionTitle: "Wish Tally社区V[DOCUMENT_VERSION]版", // Wish Tally Community V2.0 - 2.6
  reportMenuMessageSuccess: "显示报告菜单栏",
  /*
   * Select Menu default error message, will display refresh name and emoji for [COMMAND_DESCRIPTION]
   */
  selectMenuMessageCacheError: "无法在消息之间切换、在最新消息上恢复或使用 [COMMAND_DESCRIPTION].",
  selectMenuMessageCacheRestarted: "已重新启动，无法移动页面使用 [COMMAND_DESCRIPTION].",
  /*
   * report-v[GENSHIN_VERSION] Command
   * Show specific Genshin Version, with all banners
   */
  reportEmoji: "\uD83D\uDCD4",
  reportCustomId: "[LOAD_REPORT_VERSION]",
  reportName: "报告",
  reportMessageError: "无法加载'v[DOCUMENT_VERSION]'中版本的社区文档可能还不存在？",
  reportMessageException: "已加载v[DOCUMENT_VERSION]文档，但版本[GENSHIN_VERSION]遇到错误，请再试一遍",
  reportMessageUnableFindVersion: "已加载v[DOCUMENT_VERSION]文档，但版本[GENSHIN_VERSION]似乎尚不存在，请再试一遍",
  reportMessageNoWishes: "已加载v[DOCUMENT_VERSION]文档, 找到版本[GENSHIN_VERSION]但没有可用的愿望，请再试一遍",
  reportMessageFound: "版本加载数据[GENSHIN_VERSION]",
  reportSelectCustomId: "[SELECT_REPORT_VERSION]",
  reportSelectIndexCustomId: "[SELECT_REPORT_INDEX]",
  reportMessageSuccess: "先是报告",
  /*
   * help Command
   * Homepage for help, will show all the steps
   */
  helpEmoji: "❓",
  helpCustomId: "[LOAD_HELP]",
  helpName: "帮助",
  helpTitle: "[EMOJI] 帮助页面",
  googleAddonEmoji: "",
  googleAddonName: "谷歌插件",
  discordServerEmoji: "",
  discordServerName: "加入服务器",
  helpStepsDescriptionLayout: "\n> [EMOJI][TITLE]",
  helpDescription: "通过使用一下反应，加载相关帮助。\n\nWish Tally是一个拥有跟踪您的愿望的谷歌Sheets插件，这是能够分享到Wish Tally社区所必须的。",
  helpStep1Title: "第一步 - [EMOJI]",
  helpStep1Description: "如何获得Wish Tally",
  helpStep2Title: "第二部 - [EMOJI]",
  helpStep2Description: "如何导入愿望",
  helpStep3Title: "第三部 - [EMOJI]",
  helpStep3Description: "如何分享Wish Tally",
  helpCommandDescription: "无需导航即可显示数据的快捷方式 [EMOJI] 命令列表",
  /*
   * help-command Command
   * List all the bot commands, useful for directly going to a specific page
   */
  helpCommandEmoji: "⌨️",
  helpCommandName: "命令",
  helpCommandTitle: "[EMOJI] 命令列表",
  helpCommandCustomId: "[LOAD_HELP_COMMAND]",
  helpCommandDescription: "使用命令导航的快捷方式",
  helpCommandDescriptionTally: "调出主菜单栏",

  helpCommandMessageDisplay: "\n`[COMMAND_NAME]`\n> [COMMAND_DESCRIPTION]",

  helpCommandTitleHelp: "[EMOJI] 帮助部分",
  helpCommandDescriptionHelp: "帮助菜单栏",
  helpCommandDescriptionHelpAddon: "获取Wish Tally插件",
  helpCommandDescriptionHelpImport: "倒入选项",
  helpCommandDescriptionHelpImportAuto: "自动导入",
  helpCommandDescriptionHelpImportManual: "手动的",
  helpCommandDescriptionHelpImportExport: "出口",
  helpCommandDescriptionHelpShare: "分享Wish Tally",

  helpCommandTitleBotStat: "[EMOJI] Bot信息",
  helpCommandDescriptionHelpLastUpdate: "显示从社区加载数据的最近更新，因为这是按计划完成的",

  helpCommandTitleData: "[EMOJI] 数据部分",
  helpCommandDescriptionReportMenu: "显示所有社区文档的摘要",
  helpCommandDescriptionReportMenuSelection: "选择特定文档进行报告，例如`!wish report-m2` 用于v2.X社区文档",
  helpCommandDescriptionReport: "声称特定Genshin Impact版本的报告，例如`!wish report-v2.4`",

  helpCommandTitleContributors: "[EMOJI] 账户",
  helpCommandDescriptionsContributor: "仅使用于分享Wish Tally的人",
  helpCommandDescriptionRankWish: "将您的五星数量与社区进行比较",
  helpCommandDescriptionRank: "先是社区内的平均等级",
  helpCommandDescriptionPity: "从Pity Checker展示您的保底",
  helpCommandDescriptionAccount: "Wish Tally贡献者的菜单栏选项",
  helpCommandDescriptionRate: "所有旗帜升级成功的汇总",



  // help-share Command
  helpShareEmoji: "🔓",
  helpShareCustomId: "[LOAD_HELP_SHARE]",
  helpShareName: "分享Wish Tally",
  helpShareTitle: "[EMOJI] 如何分享Wish Tally",

  helpShareMessageDescription: "您必须加入Wish Tally Discord服务器, 才能相信您的共享连接发送消息。\n<[URL]>",
  helpShareMessage2Title: "提供分享链接",
  helpShareMessage2Description: "转到工具栏菜单, `File`然后`Share`",
  helpShareMessage3Title: "编辑权限",
  helpShareMessage3Description: "通过单击`更改为指导连接的任何人`来更改共享限制",
  helpShareMessage4Title: "每个人都有链接",
  helpShareMessage4Description: "检查3a设置为`查看器`, 因为我的脚本只需要获得全县即可查看工作表。\n单击`复制链接`3b向我提供您的Wish Tally文档。\n请单击`完成`3c",
  helpShareMessage5Title: "直接发给ModMail消息",
  helpShareMessage5Description: "将您的共享连接发送到BOT ModMail",
  helpShareMessage6Title: "选择Discord服务器",
  helpShareMessage6Description: "告诉ModMail您希望将消息发送到`Wish Tally - Genshin Impact Pity Tracker`。点击正确的号码....",
  helpShareMessage7Title: "确认信息",
  helpShareMessage7Description: "你应该从ModMail收到确认消息，工作人员会从那里问您提供帮助。",
  /*
   * help-addon Command
   */
  helpAddonEmoji: "📝",
  helpAddonCustomId: "[LOAD_HELP_ADDON]",
  helpAddonName: "获取Wish Tally",
  helpAddonTitle: "[EMOJI] 如何获取Wish Tally",
  helpAddonMessageDescription: "**Wish Tally是谷歌官方插件**\n插件获取得谷歌批准后，即使您制作了多张新的空白表格，此方法也只会被询问**一次**。安装次插件时，谷歌也没有大的警告消息。\n\n__访问此处安装插件__\n<[URL]>\n\n",
  helpAddonMessage2Title: "安装插件",
  helpAddonMessage2Description: "通过全县淡出窗口安装Wish Tally",
  helpAddonMessage3Title: "只扩空白电子表格",
  helpAddonMessage3Description: "安装插件后，您可以将其分配及任何电子表格文档。只需从<[URL]>或工具栏`File` -> `New` -> `Spreadsheet`创建一个新的电子表格",
  helpAddonMessage4Title: "其用插件",
  helpAddonMessage4Description: "要为脚本提供完全访问权限，您必须告诉谷歌为这个新创建的电子表格使用插件。\n转到 `Toolbar Extensions` -> `Add-ons` -> `Manage add-ons`",
  helpAddonMessage5Title: "启用Wish Tally",
  helpAddonMessage5Description: "选择管理加载项后会淡出一个窗口。转到三个点，然后转到`在本文档中使用`以启用Wish Tally插件。",
  helpAddonMessage6Title: "刷新您的页面",
  helpAddonMessage6Description: "**重要** - 刷新文档会自动将区域设置更改为`英国`, 这样做是为了让公示期作用。\n\n使用刷新按钮或`F5`强制刷新加载页面。",
  helpAddonMessage7Title: "初始化文档",
  helpAddonMessage7Description: "使用`扩展名` -> `Wish Tally` -> `初始化` 开始加载Wish Tally所需的所有工作表。",
  /*
   * help-import Command
   */
  helpImportEmoji: "📥",
  helpImportCustomId: "[LOAD_HELP_IMPORT]",
  helpImportName: "导入愿望",
  helpImportTitle: "[EMOJI] 如何导入愿望",
  helpImportDescription: "有多种方法可以在 Wish Tally 文档中添加愿望，以帮助避免在输入您应该做的愿望时出现人为错误`自动导入`。",
  helpImportDescriptionAutoTitle: "[EMOJI] 自动导入 (推荐的)",
  helpImportDescriptionAuto: "访问愿望历史是需要您登录游戏并提取URL。",
  helpImportDescriptionManualTitle: "[EMOJI] 手动导入",
  helpImportDescriptionManual: "只需直接`复制`和`粘贴`愿望，无需使用API。必须了解如何使用覆盖咧，否则希望全部出问题，用可用的工具可以帮助简化此方法。",
  helpImportDescriptionExportTitle: "[EMOJI] 将导出文件转换为Wish Tally",
  helpImportDescriptionExport: "如果您从其他Wish Tracker备份了您的愿望，您可以使用到处转换器。",
  /*
   * help-import-auto Command
   */
  helpImportAutoEmoji: "🖥️",
  helpImportAutoCustomId: "[LOAD_HELP_IMPORT_AUTO]",
  helpImportAutoName: "自动导入",
  helpImportAutoTitle: "[EMOJI] 自动导入愿望",
  
  helpImportAutoMessageDescription: "这是为了帮助使用米哈游API自动将愿望数据导入您的愿望清单表。\n\n然后，它会使用密钥直接代表您与 miHoYo 通信，以检查您在游戏中的愿望历史记录，并将任何新发现的愿望存储到您的愿望清单表中。 您不需要手动输入覆盖，因为这是自动为您完成的。\n\n您仍然可以使用复制和粘贴方法作为保存愿望历史记录的更安全方法，但如果您想使用这个更简单的选项，那么您 可以按照以下步骤操作：\n**请注意，任何较旧/过去 6 个月的愿望都无法通过这种方式检索，您必须在它们不再可见之前将其保存。**",
  helpImportAutoMessage2Title: "电脑的第一部分 - 生成网址",
  helpImportAutoMessage2Description: "登陆Genshin Impact，打开愿望菜单病房愿望历史向信息（无论您查看哪个旗帜历史）。这将在您的Genshin Impact日志文本文件中生成URL。",
  helpImportAutoMessage3Title: "第二部分 - 查找日志文件",
  helpImportAutoMessage3Description: "在窗户中打开文件浏览器，找到你游戏安装文件夹，在\n`Genshin Impact\\Genshin Impact Game\\GenshinImpact_Data//webcaches//Cache//Cache_Data\\找到\data_2`文件`",
  helpImportAutoMessage4Title: "第三部分 - 提取网址",
  helpImportAutoMessage4Description: "在文本文件底部附近，你将看到以:\n\n```https://hk4e-api-os.hoyoverse.com/............game_biz=h4e_global```\n\n高亮显示并复制整个URL文本",
  helpImportAutoMessage5Title: "第四部分 - 复制网址",
  helpImportAutoMessage5Description: "在文本文件的底部附近，您会看到以以下开头的URL\n\n```https://webstatic-sea.mihoyo.com/............game_biz=h4e_global#/log```\n\n突出显示并辅之争哥URL文本",
  helpImportAutoMessage6Title: "第五部分 - 开始自动导入",
  helpImportAutoMessage6Description: "确保下拉选项设置为`从米哈游自动导入`，然后单击倒入图标开始。",
  helpImportAutoMessage7Title: "第六部分",
  helpImportAutoMessage7Description: "将URL粘贴到自动导入淡出窗口中，然后按`OK`。",
  helpImportAutoMessage8Title: "中国服务器",
  helpImportAutoMessage8Description: "使用B3中的下拉选项在`设置`表中将服务器更改`中国`。再继续使用自动导入之前。",
  /*
   * help-import-manual Command
   */
  helpImportManualEmoji: "🖱️",
  helpImportManualCustomId: "[LOAD_HELP_IMPORT_MANUAL]",
  helpImportManualName: "手动导入",
  helpImportManualTitle: "[EMOJI] 手动倒入愿望",
  helpImportManualMessageDescription: "在Wish Tally中，您可以手动复制和粘贴您的愿望历史记录，作为使用自动导入的另一种选择。此方法不需要额外的工具，但重要的是使用覆盖咧进行10次愿望拉动（相同的日期和时间），以确保愿望一正确的顺序准确存储。",
  helpImportManualMessage2Title: "第一部分 - 将愿望历史复制到Wish Tally",
  helpImportManualMessage2Description: "转到愿望菜单并使用相应的拣选则`历史记录`。\n\n然后突出显示的信息并使用`CTRL+C`快捷方式复制（仅用右键单击）。",
  helpImportManualMessage3Title: "第二部分",
  helpImportManualMessage3Description: "从`仪表板`，转到电子表格中相应的愿望历史记录页面。",
  helpImportManualMessage4Title: "粘贴值",
  helpImportManualMessage4Description: "接下来，在A列中安一个空单元格，然后按`CTRL + V`或`CTRL+ Shift + V`（仅粘贴值）",
  helpImportManualMessage5Title: "粘贴问题",
  helpImportManualMessage5Description: "如果粘贴值如下所示，则需要在粘贴是避免使用右键单击选项菜单。",
  helpImportManualMessage6Title: "第三部分 - 使用覆盖管理10-Wish Pulls（非常重要）",
  helpImportManualMessage6Description: "10 multi中的所有愿望都将具有相同的时间戳和日期。\n\n因为Genshin愿望历史是从最近到醉酒显示的，我们可以假设10 multi中的最后一个条目是愿望编号1。\n\n在一下示例中，列表底部的乌鸦弓将是第一个拉动",
  helpImportManualMessage7Title: "",
  helpImportManualMessage7Description: "粘贴值[CTRL+V]并通过渐入相应的数字手动分配覆盖。",
  helpImportManualMessage8Title: "",
  helpImportManualMessage8Description: "继续到下一页（例如，在13之后继续到第14页）并对剩余的10个多重执行相同的操作。",
  helpImportManualMessage9Title: "第四部分 - 按顺序排列愿望",
  helpImportManualMessage9Description: "由于愿望历史的顺序，需要对粘贴的值进行排序。\n\n确保所有多愿望都输入了覆盖数字，否则排序将全部错误。\n\n准备好后，单击工作表顶部的“排序”按钮。\n\n应用排序后，覆盖将自动按日期和时间顺序对多愿望 1 到 10 和单一愿望进行排序。",
  /*
   * help-import-export Command
   */
  helpImportExportEmoji: "⛏️",
  helpImportExportCustomId: "[LOAD_HELP_IMPORT_EXPORT]",
  // List of options
  helpImportExportMessageOptionLayout: "\n[PROJECT_NAME] `[FILE_TYPE]`- <[URL]>",
  exportOption1ProjectName: "Genshin愿望出口",
  exportOption1FileType: "XLSX文件",
  exportOption1URL: "https://github.com/biuuu/genshin-wish-export",
  exportOption2ProjectName: "Genshin愿望",
  exportOption2FileType: "CSV文件",
  exportOption2URL: "https://genshin-wishes.com",
  exportOption3ProjectName: "paimon.moe",
  exportOption3FileType: "XLSX愿望",
  exportOption3URL: "https://paimon.moe",

  helpImportExportName: "出口 进口",
  helpImportExportTitle: "[EMOJI] 从出口进口愿望",
  helpImportExportMessageDescription: "使用此转换器文档来帮助转换您对 Wish Tally 的愿望。\n<[URL]>\n\n**支持的导出文件**",

  helpImportExportMessage2Title: "制作电子表格的副本",
  helpImportExportMessage2Description: "在访问电子表格之前，您需要先拥有一个 Google 帐户。 将此电子表格的副本复制到您的谷歌云端硬盘中。\n<[URL]>\n\n在`文件`菜单工具栏中, 点击`制作副本`。 这会将电子表格的副本创建到您的谷歌云端硬盘中，然后您可以对其进行修改以存储您自己的愿望历史记录。\n\n将出现`复制文档`淡出窗口，您可以在`名称`部分重命名文档，单击`确定`会讲Wish Tally转换的副本保存到您的谷歌Drive",
  helpImportExportMessage3Title: "检查README",
  helpImportExportMessage3Description: "要了解有关如何使用转换器文档的更多信息，请查看`README`表",
}