module.exports = {
  // Discord Emoji List
  // https://emzi0767.gl-pages.emzi0767.dev/discord-emoji/discordEmojiMap-canary.json
  makerUserId:"358320066770501632",
  discordEmbedLengthLimit: 10,
  contentsName: "Contents", // Name of field
  contentsNameSelection: "\uD83D\uDD33",
  contentsNameDeselection: "▫️",

  displayAll: "All",
  displayNone: "None",
  displayTotal: "Total",
  displayGrandTotal: "Grand Total",
  displayAverageShorthand: "avg.",
  displayOtherItems: "Other",
  displayBannerName: {
    "Character Event Banner": "Character Event Banner",
    "Weapon Event Banner": "Weapon Event Banner",
    "Permanent Banner": "Permanent Banner",
    "Novice Banner": "Novice Banner",
  },
  displayItemType: {
    "Character": "Character",
    "Weapon": "Weapon",
  },

  rarity5StarEmoji: "⋆⋆⋆⋆⋆",
  rarity5StarName: "5 Star",
  rarity4StarEmoji: "⋆⋆⋆⋆",
  rarity4StarName: "4 Star",
  rarity3StarEmoji: "⋆⋆⋆",
  rarity3StarName: "3 Star",
  refreshName: "Reload",
  refreshEmoji: "🔄",
  statusSuccessName: "Success",
  statusSuccessEmoji: "✅",
  statusErrorName: "Error",
  statusErrorEmoji: "❌",
  statusLoadingName: "Loading",
  statusLoadingEmoji: "📂",
  statusCheckingName: "Checking",
  statusCheckingEmoji: "⏳",
  statusProcessingName: "Processing..",
  statusProcessingEmoji: "⏳",
  statusLoadedEmoji: "✅",
  statusLoadedName: "Loaded",
  statusLoadingEmoji: "⏳",
  statusLoadingName: "Is Loading",
  statusLoadEmoji: "❌",
  statusLoadName: "Not Loaded",

  urlImageError: "https://cdn.discordapp.com/attachments/814486266618970162/940599883658842122/error_1.png",
  urlImage5Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801560898850907/Final_5_Star.png",
  urlImage4Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801559669923940/Final_4_Star.png",
  urlImageTally: "https://cdn.discordapp.com/attachments/814486266618970162/859426718754275399/Wish-Tally---Community.png",
  urlExportConvertor: "https://docs.google.com/spreadsheets/d/1lXGo_pKxKmTzd9pg1b1gr6Fa-zfcM2ZQd0EnFfzg8Dk/edit",
  urlDiscordInvite: "https://discord.gg/CKuJSbtndV",
  urlGoogleWishTallyAddon: "https://workspace.google.com/marketplace/app/wish_tally/791037722195",
  urlGoogleSheet: "https://docs.google.com/spreadsheets/u/0/",
  // output message
  replaceCodeURL: "[URL]",
  replaceCodeTitle: "[TITLE]",
  replaceCodeProjectName: "[PROJECT_NAME]",
  replaceCodeFileType: "[FILE_TYPE]",
  replaceCodeStatus: "[STATUS]",
  replaceCodeRank: "[RANK]",
  replaceCodeCommandName: "[COMMAND_NAME]",
  replaceCodeEmoji: "[EMOJI]",
  replaceCodeStatusEmoji: "[EMOJI_STATUS]",
  replaceCodeAccountId: "[ACCOUNT_ID]",
  replaceCodeAccountsMax: "[ACCOUNTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeCommandDescription: "[COMMAND_DESCRIPTION]",
  replaceCodeLanguage: "[LANGUAGE]",
  replaceCodeParameter: "[PARAMETER]",
  replaceCodeDate: "[DATE]",
  replaceCodeDocumentVersion: "[DOCUMENT_VERSION]",
  replaceCodeGenshinVersion: "[GENSHIN_VERSION]",
  replaceCodeAttemptIndex: "[ATTEMPTS_INDEX]",
  replaceCodeAttemptMax: "[ATTEMPTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeValue:"[VALUE]",
  replaceCodePercentage:"[PERCENTAGE]",
  outputContent: "[COMMAND_NAME]|[EMOJI_STATUS]|For <@[USER_ID]> |[LANGUAGE]|[PARAMETER]|[COMMAND_DESCRIPTION] [DATE]",

  latestVersionCustomId: "[LOAD_LATEST_VERSION]",
  latestVersionName: "Latest Version",
  latestVersionEmoji: "🔎",
  latestVersionTitle: "[EMOJI] Genshin Impact Version [GENSHIN_VERSION]",
  // ping Command
  replaceCodeBotName: "[BOT_NAME]",
  pingMessage: ":wave: [BOT_NAME] I'm still alive",
  // last-update Command
  lastUpdateMessageError: "Please wait for the Community Cache sheet to load, status: [STATUS]",
  lastUpdateMessageException: "Error unable to load Community Cache data, status: [STATUS]",
  lastUpdateName: "Last Update",
  lastUpdateTitle: "Community Document Last Update Summary",
  lastUpdateEmoji: "⏲️",
  lastUpdateCustomId: "[LOAD_LAST_UPDATE]",
  lastUpdateDocumentTitle: "Community V[DOCUMENT_VERSION].X",

  lastUpdateStatusCommunityAccounts: "Community Account Document",
  lastUpdateStatusLanguagePadding: 18,
  lastUpdateStatusDocumentPadding: 16,
  lastUpdateStatusDocument: "DOCUMENT LOADED",
  lastUpdateStatusDocumentAccount: "ACCOUNTS REFRESH",
  lastUpdateStatusDocumentCache: "CACHE REFRESH",
  lastUpdateStatusDocumentWishes: "BANNER REFRESH",
  lastUpdateStatusCommunityPadding: 15,
  lastUpdateStatusItemsByBanner: "ITEMS BY BANNER",
  lastUpdateStatusAccounts: "ACCOUNTS",
  lastUpdateStatusCharacterBannerPity: "PITY",
  lastUpdateStatusDatePadding: 5,
  lastUpdateStatusStartDate: "START",
  lastUpdateStatusEndDate: "END",
  lastUpdateStatusSummaryPadding: 14,
  lastUpdateStatusDuration: "DURATION",
  lastUpdateStatusAttempts: "ATTEMPTS",
  lastUpdateStatusMaxAccounts: "MAX ACCOUNTS",
  lastUpdateStatusTotalWishes: "TOTAL WISHES",
  lastUpdateStatusCurrentUpdates: "ACCOUNT CHECK",
  lastUpdateStatusHour: "hour",
  lastUpdateStatusHours: "hours",
  lastUpdateStatusAnd: "and",
  lastUpdateStatusMinute: "minute",
  lastUpdateStatusMinutes: "minutes",
  lastUpdateStatusAgo: "ago",
  /*
   * account Command
   */
  accountEmoji: "🔑",
  accountCustomId: "[LOAD_ACCOUNT]",
  accountName: "Account",
  accountTitle: "[EMOJI] Account",
  accountDescriptionFound: "Thank you for contributing to the Wish Tally Community, currently there is data for [ACCOUNTS_MAX] accounts.\n\nHere are the options that is exclusive for you.",
  accountDescriptionNotFound: "Sorry we cannot find your Wish Tally account, there are [ACCOUNTS_MAX] accounts available but none is linked to your Discord Account.\n\nPlease visit the help page to find out how to contribute to the Wish Tally Community.\n\nIf you have recently shared your Account on ModMail, you must wait for staff to check your document.",
  accountDescriptionNotLoadedAccount: "Bot has recently cleared the cache, it will reload the accounts soon. For now the buttons are all enabled, but these command still require linkage to your Wish Tally account.",
  accountDescriptionLayout: "\n> [EMOJI][COMMAND_NAME] - [COMMAND_DESCRIPTION]",
  accountDescriptionRank: "Display your total wishes between each Community Document, and show your average pity rank.",
  accountDescriptionWish: "Display your wish contribution by rank, useful in knowing which Genshin Version was popular among the community.",
  accountDescriptionPity: "Extracts your latest pity from your document, to showcase people your wishes without the need to take a screenshot.",
  accountDescriptionRate: "Show all win rates for limited time characters in  `Character Event banners`.",
  /*
   * rank Command
   */
  rankEmoji: "🏆",
  rankCommunityEmoji: "🌎",
  rankCustomId: "[LOAD_RANK]",
  rankName: "Rank",
  rankAccountTitle: "Account Summary",
  rankTitle: "Rank Summary",
  rankDescription: "Personal Rank is your ranking using the data from your Wish Tally document, Community Rank is all the accounts average which means the lower the number the better your rank is.",
  rankCommunityTitle: "[EMOJI] Community Ranking",
  rankPersonalTitle: "[EMOJI] Personal Ranking",
  rankNoWishes: "No wishes made during this version.",
  /*
   * rank-wish Command
   */
  rankWishEmoji: "✨",
  rankWishCustomId: "[LOAD_RANK_WISH]",
  rankWishName: "Wish",
  rankWishLimit: 15,
  rankWishGenshinVersionLimit: 5,
  rankWishGenshinVersionSameLimit: 2,
  rankWishLimitPadding: 2,
  rankWishSameTotalLimit: 3,
  rankWishSameTotalMessage: "__Hidden [STATUS] Accounts that is rank [RANK]__",
  rankWishTitle: "Wishes Ranking",
  rankWishNotReadyMessage: "Wishes data by accounts has not been loaded, please try again.\n[STATUS]",
  rankWishLoadedMessage: "Rank by wishes has successfully loaded",
  rankWishYouEmoji: "👈",
  rankWishRarity4StarEmoji: "4⭐",
  rankWishRarity5StarEmoji: "5⭐",
  rankWishSelectVersionDefaultPlaceholderForAll: "All Community Data",
  rankWishRankTitle: "Wish Tally Community V",
  rankWishRankGenshinTitle: "Genshin Version V",
  rankWishDocumentTitle: "Wish Tally Community V[DOCUMENT_VERSION].X",
  rankWishSelectVersionAllId: "[SELECT_RANK_WISH_VERSION_ALL]",
  rankWishSelectBannerIndexId: "[SELECT_RANK_WISH_BANNER_INDEX]",
  rankWishSelectVersionIndexId: "[SELECT_RANK_WISH_VERSION_INDEX]",
  rankWishMessageSuccessSelect: "Navigating between banners",
  rankWishMessageError: "Encountered error, try again another time",

  checkCommunityAccountMessageError: "Please wait for the Community Accounts sheet to load, status: [STATUS]",
  // finding account only show for error
  findingAccountName: "Finding Account",
  findingAccountEmoji: "🔎",
  findingAccountMessageNotFound: "Error! Unable to find your account details data from Community Account\nIf you have not joined the community go to Help page to find out how to share your Wish Tally Document, if you recently have please wait for Community to update.",
  findingAccountMessageException: "Error! Unable to extract data from Community Document [DOCUMENT_VERSION].",
  findingAccountMessageError: "Error unable to find Community Account sheet",

  displayRankMessageError: "Error unable to find Community Document [DOCUMENT_VERSION].",
  displayRankMessageNotFound: "Community Document [DOCUMENT_VERSION], does not have your account details yet. Your Account position is [ACCOUNT_ID] while there is [ACCOUNTS_MAX] accounts available, please wait for the Community to update.",
  displayRankMessageException: "Error! Unable to extract data from Community ",
  /*
   * pity Command
   */
  pityEmoji: "🧮",
  pityCustomId: "[LOAD_PITY]",
  pityName: "Pity",
  pityMessageError: "Error to load your document",
  pityMessageLoading: "Loading document [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] attempts.",
  pityMessageUnableLoad: "Error unable to load your document, try again later.",
  pityMessageUnableFind: "Error unable to find `Pity Checker` sheet from document.",
  pityMessageLoadingPity: "Loading `Pity Checker` sheet data [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] attempts.",
  pityMessageUnablePityExtract: "Error extracting from `Pity Checker` sheet has totally failed, try again later.",
  pityMessagePitySheetOld: "Your Document 'Pity Checker' sheet is out of date, check <#836651770100842576>.",
  pityMessagePitySheetSuccess: "Displaying pity from your document",
  pityCurrentWishNumber: "Current Wish Number",
  pityBackCustomId: "[LOAD_PITY_BACK]",
  pityNextCustomId: "[LOAD_PITY_NEXT]",
  pityBackEmoji: "⭐", // Back
  pityBackTitle: "⭐⭐⭐⭐⭐", // Back
  pityBackNoEarned: "⭐⭐⭐⭐⭐ - No 5 Star found", // Back
  pityBackName: "5 Star", // Back
  pityNextEmoji: "⭐", // Next
  pityNextTitle: "⭐⭐⭐⭐", // Next
  pityNextNoEarned: "⭐⭐⭐⭐ - No 4 Star found", // Next
  pityNextName: "4 Star", // Next
  /*
   * rate Command
   */
  rateEmoji: "🎯",
  rateCustomId: "[LOAD_RATE]",
  rateVersionCustomId: "[LOAD_RATE_VERSION]",
  rateName: "Rate",
  rateTitle: "[EMOJI] Rate",
  rateDescriptionSelection: "**Key**\n👎 - Could not get rated character\n✌️ - Beaten 50/50\n👍 - Earned using previous pity\n🙌 - Used pity on current banner\n~~Choose which document version that you wish to see in more detail~~ Soon.",
  rateMessageError: "Encountered error when loading the Character Banner Pity, try again another time",
  rateNotReadyMessage: "Character Banner Pity is still loading, please try again.\n[STATUS]",
  rateLoadedMessage: "Rate has successfully loaded",
  rateMenuSelectDocumentVersionPlaceholder: "Select Wish Tally Community Data",
  rateMenuSelectDocumentVersionCustomId: "[SELECT_RATE_MENU_VERSION]",
  rateMenuSelectDocumentVersionSelection: "Wish Tally Community V[DOCUMENT_VERSION].X",
  rateBannerDisplayLayout: "\n**Version [GENSHIN_VERSION]**",
  rateInnerBannerDisplayLayout: "\n__[TITLE]__",
  rateItemDisplayLayout: "\n> [TITLE]",
  rateFirstBanner: "First Banner",
  rateSecondBanner: "Second Banner",
  rateThirdBanner: "Third Banner",
  rateFourthBanner: "Fourth Banner",
  rateFifthBanner: "Fifth Banner",
  rateEmptyTotal: "None earned",
  rateTotalTitle: "Total",
  rateResultLayout: "`[TITLE] [VALUE]`",
  rateTotalMaxPadding: 4,
  ratePercentageMaxPadding: 3,
  rateWinEmoji: "✅",
  rateWinName: "", // Not in use
  rateLoseEmoji: "❌",
  rateLoseName: "", // Not in use

  rateFailedToGetEmoji: "👎",
  rateFailedToGetName: "Failed",
  rateFailedToGetDetailed: "Could not get rated character",
  rateWonFiftyFiftyEmoji:"✌️",
  rateWonFiftyFiftyName:"Beat 50/50",
  rateWonFiftyFiftyDetailed:"Beaten 50/50",
  rateUsedPityEmoji: "👍",
  rateUsedPityName: "Used Pity",
  rateUsedPityDetailed: "Earned using previous pity",
  rateSkippedEmoji: "👉", // Not in use
  rateSkippedName: "Skip", // Not in use
  rateSkippedDetailed: "No 5-Star Attempts",
  rateSecondAttemptEmoji: "🙌",
  rateSecondAttemptName: "Used Current Pity",
  rateSecondAttemptDetailed: "Used pity on current banner",
  rateResultLeftPercentageLayout: "[EMOJI]`[VALUE]|[PERCENTAGE]%`",
  rateResultCenterPercentageLayout: "▰",
  rateResultRightPercentageLayout: "`%[PERCENTAGE]|[VALUE]`[EMOJI]",
  rateResultPercentageCovered: "▰",
  rateResultPercentageUncovered: "▱",

  languageSelectByNameCustomId: "[SELECT_LANGUAGE_NAME]",
  /*
   * tally Command
   */
  tallyEmoji: "\uD83E\uDEA7",
  tallyCustomId: "[LOAD_TALLY]",
  botEmoji: "<:wish_tally:1015215165500825611>",
  tallyName: "Menu",
  tallyTitle: "[EMOJI] Wish Tally Bot",
  tallyDescription: "**[EMOJI] Welcome to the Wish Tally Menu**\n__Bot is managed by <@[USER_ID]>__",
  tallyDescriptionBot: "Use the buttons below to control the [EMOJI] Wish Tally bot.",
  tallyDescriptionHelp: "Only data from with Wish Tally Community is shown here, check the [EMOJI] Help Page to get involved. \n\n**Please note** that __only the person requested the bot can control the bot__.",
  /*
   * report-m[DOCUMENT VERSION] Back Command
   */
  reportDocumentEmoji: "\uD83D\uDCD4",
  reportDocumentCustomId: "[LOAD_COMMUNITY_VERSION]",
  reportDocumentName: "Document",
  /*
   * report-m Command Load all doc
   */
  reportMenuEmoji: "<:wish_tally_community:1015216582231871611>",
  reportMenuCustomId: "[LOAD_COMMUNITY]",
  reportMenuName: "Community",
  reportMenuResetCustomId: "[LOAD_COMMUNITY_RESET]",
  reportMenuResetEmoji: "🗑️",
  reportMenuResetName: "Reset Filter",
  reportMenuMessageError: "Unable to load Community Document for Version `[DOCUMENT_VERSION]` may not exist yet?",
  reportMenuMessageErrorLoading: "Community Document for Version `[DOCUMENT_VERSION]` has not loaded yet.",
  reportMenuMessageException: "Error encountered unable to load report Community Document Version `[DOCUMENT_VERSION]`, please try again?",
  reportMenuMessageNoData: "No data to display for loading Community Document Version `[DOCUMENT_VERSION]`, please try again?",
  reportMenuMessageFound: "Displaying Community Document Version `[DOCUMENT_VERSION]`",
  reportMenuDefaultPlaceholderForAll: "All Community Data",
  reportMenuSelectCustomId: "[SELECT_REPORT_MENU_VERSION]",
  reportMenuSelectAllId: "[SELECT_REPORT_MENU_ALL]",
  reportMenuSelectGensionVersionCustomId: "[SELECT_GENSHIN_VERSION]",
  reportMenuSelectGenshinVersionPlaceholder: "Select Genshin Impact Version",
  reportMenuSelectGensionVersionName: "Genshin Impact V[GENSHIN_VERSION]",
  reportMenuSelectIndexCustomId: "[SELECT_REPORT_MENU_INDEX]",
  reportMenuDocumentTitle: "Wish Tally Community V[DOCUMENT_VERSION].X",
  reportMenuDocumentSelectionTitle: "Wish Tally Community V[DOCUMENT_VERSION]", // Wish Tally Community V2.0 - 2.6
  reportMenuMessageSuccess: "Displaying report menu",
  /*
   * Select Menu default error message, will display refresh name and emoji for [COMMAND_DESCRIPTION]
   */
  selectMenuMessageCacheError: "Cannot switch between message, resume on latest message or use [COMMAND_DESCRIPTION].",
  selectMenuMessageCacheRestarted: "Bot has restarted, unable to move pages use [COMMAND_DESCRIPTION].",
  /*
   * report-v[GENSHIN_VERSION] Command
   * Show specific Genshin Version, with all banners
   */
  reportEmoji: "\uD83D\uDCD4",
  reportCustomId: "[LOAD_REPORT_VERSION]",
  reportName: "Report",
  reportMessageError: "Unable to load community document for Version [GENSHIN_VERSION] in the 'v[DOCUMENT_VERSION]' may not exist yet?",
  reportMessageException: "Loaded v[DOCUMENT_VERSION] document but version [GENSHIN_VERSION] has encountered an error, please try again",
  reportMessageUnableFindVersion: "Loaded v[DOCUMENT_VERSION] document but version [GENSHIN_VERSION] doesn't seem to exist yet, please try again",
  reportMessageNoWishes: "Loaded v[DOCUMENT_VERSION] document, found version [GENSHIN_VERSION] but no wishes available, please try again",
  reportMessageFound: "Loaded data for version [GENSHIN_VERSION]",
  reportSelectCustomId: "[SELECT_REPORT_VERSION]",
  reportSelectIndexCustomId: "[SELECT_REPORT_INDEX]",
  reportMessageSuccess: "Displaying report",
  /*
   * help Command
   * Homepage for help, will show all the steps
   */
  helpEmoji: "❓",
  helpCustomId: "[LOAD_HELP]",
  helpName: "Help",
  helpTitle: "[EMOJI] Help Page",
  googleAddonEmoji: "",
  googleAddonName: "Google Addon",
  discordServerEmoji: "",
  discordServerName: "Join Server",
  helpStepsDescriptionLayout: "\n> [EMOJI][TITLE]",
  helpDescription: "By using the reactions below, load the relevant help.\n\nWish Tally is a Google Sheet Addon that is used to keep track of your wishes, this is needed to be able to share to the Wish Tally Community.",
  helpStep1Title: "Step 1 - [EMOJI]",
  helpStep1Description: "How to get Wish Tally",
  helpStep2Title: "Step 2 - [EMOJI]",
  helpStep2Description: "How to Import Wishes",
  helpStep3Title: "Step 3 - [EMOJI]",
  helpStep3Description: "How to Share Wish Tally",
  helpCommandDescription: "Short cut in displaying data without navigating from the [EMOJI] Command List",
  /*
   * help-command Command
   * List all the bot commands, useful for directly going to a specific page
   */
  helpCommandEmoji: "⌨️",
  helpCommandName: "Commands",
  helpCommandTitle: "[EMOJI] Command List",
  helpCommandCustomId: "[LOAD_HELP_COMMAND]",
  helpCommandDescription: "Shortcut in navigating with commands",
  helpCommandDescriptionTally: "Bring up the main menu",

  helpCommandMessageDisplay: "\n`[COMMAND_NAME]`\n> [COMMAND_DESCRIPTION]",

  helpCommandTitleHelp: "[EMOJI] Help Section",
  helpCommandDescriptionHelp: "Help Menu",
  helpCommandDescriptionHelpAddon: "Get Wish Tally Addon",
  helpCommandDescriptionHelpImport: "Import Options",
  helpCommandDescriptionHelpImportAuto: "Auto Import",
  helpCommandDescriptionHelpImportManual: "Manual",
  helpCommandDescriptionHelpImportExport: "Export",
  helpCommandDescriptionHelpShare: "Share Wish Tally",

  helpCommandTitleBotStat: "[EMOJI] Bot Information",
  helpCommandDescriptionHelpLastUpdate: "Display last update for loading data from Community, as this is done on a schedule",

  helpCommandTitleData: "[EMOJI] Data Section",
  helpCommandDescriptionReportMenu: "Display summary of all the community document",
  helpCommandDescriptionReportMenuSelection: "Select specific document for reporting, e.g `!wish report-m2` for v2.X community document",
  helpCommandDescriptionReport: "Generate report on a specific Genshin Impact version, e.g `!wish report-v2.4`",

  helpCommandTitleContributors: "[EMOJI] Account",
  helpCommandDescriptionsContributor: "Only for people that shared their Wish Tally",
  helpCommandDescriptionRankWish: "Compare your number of 5-Star with the community",
  helpCommandDescriptionRank: "Display average rank within the Community",
  helpCommandDescriptionPity: "Showcase your Pity from Pity Checker",
  helpCommandDescriptionAccount: "Menu options for Wish Tally contributors",
  helpCommandDescriptionRate: "Summary of all banners rate-up success",



  // help-share Command
  helpShareEmoji: "🔓",
  helpShareCustomId: "[LOAD_HELP_SHARE]",
  helpShareName: "Share Wish Tally",
  helpShareTitle: "[EMOJI] How to Share Wish Tally",

  helpShareMessageDescription: "You must join the Wish Tally Discord server, to message your sharing link.\n<[URL]>",
  helpShareMessage2Title: "Providing a Share Link",
  helpShareMessage2Description: "Go to the toolbar menu, `File` and then `Share`",
  helpShareMessage3Title: "Edit Permission",
  helpShareMessage3Description: "Change the sharing restrictions by clicking on `Change to anyone with the link`",
  helpShareMessage4Title: "Everyone with the URL",
  helpShareMessage4Description: "Check 3a is set as a `Viewer`, as my script just need permission to see the sheet.\nClick on `Copy Link` 3b to provide me the link to your Wish Tally sheet.\nTo confirm the changes click on `Done` 3c",
  helpShareMessage5Title: "Direct Message ModMail",
  helpShareMessage5Description: "Send your sharing link to the BOT ModMail",
  helpShareMessage6Title: "Choose Discord Server",
  helpShareMessage6Description: "Tell ModMail that you wish to send message to `Wish Tally - Genshin Impact Pity Tracker`. Click on the correct number....",
  helpShareMessage7Title: "Confirmation message",
  helpShareMessage7Description: "You should get a confirmation message from ModMail, the staff will assist you from there.",
  /*
   * help-addon Command
   */
  helpAddonEmoji: "📝",
  helpAddonCustomId: "[LOAD_HELP_ADDON]",
  helpAddonName: "Get Wish Tally",
  helpAddonTitle: "[EMOJI] How to get Wish Tally",
  helpAddonMessageDescription: "**Wish Tally is an Official Google Add-On**\nWith the Add-on being approved by Google, this method will only be asked **once**, even if you make multiple new blank Sheets. There is no big warning message from Google when installing this Add-on too.\n\n__Visit here to install the Add-on__\n<[URL]>\n\n",
  helpAddonMessage2Title: "Install Add-On",
  helpAddonMessage2Description: "Go through the permission popup to install Wish Tally",
  helpAddonMessage3Title: "Make a blank Spreadsheet",
  helpAddonMessage3Description: "After you have the add-on installed, you can assign it to any spreadsheet document. Just create a new spreadsheet from either <[URL]> or toolbar `File` -> `New` -> `Spreadsheet`",
  helpAddonMessage4Title: "Enabling the Add-on",
  helpAddonMessage4Description: "To provide full access for the script you must tell Google to use the add-on for this newly created spreadsheet.\nGo to the `Toolbar Extensions` -> `Add-ons` -> `Manage add-ons`",
  helpAddonMessage5Title: "Enable Wish Tally",
  helpAddonMessage5Description: "A window will popup after selecting manage add-ons. Go to the 3 dots and then go to `Use in this document` to enable Wish Tally add-on.",
  helpAddonMessage6Title: "Refresh your Page",
  helpAddonMessage6Description: "**IMPORTANT** - Refreshing the document will automatically change the locale to `United Kingdom`, this is done in order to allow the formula to work.\n\nUse the refresh button or `F5` to force the page to reload.",
  helpAddonMessage7Title: "Initialise the Document",
  helpAddonMessage7Description: "Use the toolbar `Extension` -> `Wish Tally` -> `Initialise` to begin loading all the sheets required for Wish Tally.",
  /*
   * help-import Command
   */
  helpImportEmoji: "📥",
  helpImportCustomId: "[LOAD_HELP_IMPORT]",
  helpImportName: "Import Wishes",
  helpImportTitle: "[EMOJI] How to Import Wishes",
  helpImportDescription: "There is multiple method of added wishes into Wish Tally document, to help avoid human error in entering wishes you should do `Auto Import`.",
  helpImportDescriptionAutoTitle: "[EMOJI] Auto Import (Recommended)",
  helpImportDescriptionAuto: "Requires you to log-in the game and extract the URL when visiting the Wish History.",
  helpImportDescriptionManualTitle: "[EMOJI] Manual Import",
  helpImportDescriptionManual: "Just `copy` and `paste` the wishes directly, without the need of using API. Must understand how to use overide column otherwise wishes are all out of order, there are tools available that helps simplify this method.",
  helpImportDescriptionExportTitle: "[EMOJI] Convert Export File to Wish Tally",
  helpImportDescriptionExport: "If you have a backup of your wishes from alternative Wish Trackers, you can use a export convertor.",
  /*
   * help-import-auto Command
   */
  helpImportAutoEmoji: "🖥️",
  helpImportAutoCustomId: "[LOAD_HELP_IMPORT_AUTO]",
  helpImportAutoName: "Auto Import",
  helpImportAutoTitle: "[EMOJI] Auto Import Wishes",
  
  helpImportAutoMessageDescription: "This is to help automatically import wish data to your Wish Tally sheet using miHoYo API.\n\nThis works by using the URL and extracting the key. With the key it will then communicates to miHoYo directly on your behalf to check your in game wish history, and store any newly found wishes to your Wish Tally sheet. You won't need to manually input override, as this is done automatically for you.\n\nYou can still use the copy and pasting method as a safer way to saving wish history, but if you want to use this simpler option then you can follow these steps:\n**Please note that any Wishes that are older/past 6 months cannot be retrieved this way, you must save them before they are no longer visible.**",
  helpImportAutoMessage2Title: "PC Step 1 - Generate URL",
  helpImportAutoMessage2Description: "Log into Genshin Impact, open up the Wish menu and visit the Wish History Details (doesn't matter which banner history you view). This will generate the URL in your Genshin Impact log text file.",
  helpImportAutoMessage3Title: "Step 2 - Finding the log file",
  helpImportAutoMessage3Description: "Open the file browser in Window and find your game installation folder to find `data_2` file at \n`Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\Cache_Data\\`",
  helpImportAutoMessage4Title: "Step 3 - Extract the URL",
  helpImportAutoMessage4Description: "Right click and `Open with` the `data_2` text file, with `Notepad`",
  helpImportAutoMessage5Title: "Step 4 - Copy the URL",
  helpImportAutoMessage5Description: "Near the bottom of the text file you'll see the URL starting with:\n\n```https://hk4e-api-os.hoyoverse.com/............game_biz=h4e_global```\n\nHighlight and copy the entire URL text",
  helpImportAutoMessage6Title: "Step 5 - Begin Auto Import",
  helpImportAutoMessage6Description: "Make sure the drop down option is set to `Auto Import from miHoYo` and click on the import icon to begin.",
  helpImportAutoMessage7Title: "Step 6",
  helpImportAutoMessage7Description: "Paste the URL within the Auto Import popup, then press `OK`.",
  helpImportAutoMessage8Title: "For China Server",
  helpImportAutoMessage8Description: "Change Server to `China` within `Settings` sheet, using the drop down option in B3. Before proceeding in using Auto Import.",
  /*
   * help-import-manual Command
   */
  helpImportManualEmoji: "🖱️",
  helpImportManualCustomId: "[LOAD_HELP_IMPORT_MANUAL]",
  helpImportManualName: "Manual Import",
  helpImportManualTitle: "[EMOJI] Manually Import Wishes",
  helpImportManualMessageDescription: "In Wish Tally, you can manually copy and paste your wish history as another alternative from using Auto Import. This method does not require additional tools, however it is important to use the override column for 10 wish pulls (same date and time), in order to ensure the wishes are stored accurately in the correct order.",
  helpImportManualMessage2Title: "Step 1 - Copy Wish History to Wish Tally",
  helpImportManualMessage2Description: "Go to the Wish menu and select 'History' using the appropriate keys.\n\nThen highlight the information like shown in the image and copy using `CTRL+C` shortcut (right click is disabled).",
  helpImportManualMessage3Title: "Step 2",
  helpImportManualMessage3Description: "From the `Dashboard`, go to the respective wish history page in your spreadsheet.",
  helpImportManualMessage4Title: "Pasting value",
  helpImportManualMessage4Description: "Next, press an empty cell in column A, and press `CTRL + V` or `CTRL+ Shift + V` (Paste Values Only)",
  helpImportManualMessage5Title: "Paste Issue",
  helpImportManualMessage5Description: "If the paste value looks like this, you would need to avoid using the Right Click Option menu when pasting.",
  helpImportManualMessage6Title: "Step 3 - Managing 10-Wish Pulls using Overrides (Very Important)",
  helpImportManualMessage6Description: "All wishes in a 10 multi will have the same timestamp and date. Because Genshin wish history is displayed from newest to oldest, we can assume the last entry in the 10 multi is wish number 1.\n\nFirst copy the history using the method shown before, then number these items in order on your spreadsheet history tab following this method.\n\nIn the following example Raven bow at the bottom of the list would be the first pull",
  helpImportManualMessage7Title: "",
  helpImportManualMessage7Description: "Paste the value [CTRL+V] and assign the override manually by typing the corresponding numbers.",
  helpImportManualMessage8Title: "",
  helpImportManualMessage8Description: "Continue onto the next page (e.g go on to Page 14 after 13) and do the same thing for the remaining 10 multi.",
  helpImportManualMessage9Title: "Step 4 - Sorting Wishes in Order",
  helpImportManualMessage9Description: "Due to the order of the wish history, the pasted value needs to be sorted.\n\nMake sure all multi wishes has override numbers inputted, otherwise the sorting will be all wrong.\n\nClick on the `SORT` button at the top of the sheet when you are ready.\n\nWhen sort is applied, the override will automatically sort multi wishes 1 to 10 and single wishes in date and time order.",
  /*
   * help-import-export Command
   */
  helpImportExportEmoji: "⛏️",
  helpImportExportCustomId: "[LOAD_HELP_IMPORT_EXPORT]",
  // List of options
  helpImportExportMessageOptionLayout: "\n[PROJECT_NAME] `[FILE_TYPE]`- <[URL]>",
  exportOption1ProjectName: "Genshin Wish Export",
  exportOption1FileType: "XLSX file",
  exportOption1URL: "https://github.com/biuuu/genshin-wish-export",
  exportOption2ProjectName: "Genshin Wishes",
  exportOption2FileType: "CSV file",
  exportOption2URL: "https://genshin-wishes.com",
  exportOption3ProjectName: "paimon.moe",
  exportOption3FileType: "XLSX file",
  exportOption3URL: "https://paimon.moe",

  helpImportExportName: "Export Import",
  helpImportExportTitle: "[EMOJI] Import Wishes from Export",
  helpImportExportMessageDescription: "Use this convertor document to help convert your wishes for Wish Tally.\n<[URL]>\n\n**Supported Export Files**",

  helpImportExportMessage2Title: "Make a Copy of the spreadsheet",
  helpImportExportMessage2Description: "You will need to have a Google account first before you can access the spreadsheet. Make a copy of this spreadsheet into your Google Drive.\n<[URL]>\n\nIn the `File` menu toolbar, click `Make a copy`. This will create a copy of the spreadsheet into your Google Drive, which you can then modify to store your own wish history.\n\nAn `Copy document` popup will appear, you can rename the document within the `Name` section, clicking on `OK` will save a copy of Wish Tally Conversion into your Google Drive",
  helpImportExportMessage3Title: "Check the README",
  helpImportExportMessage3Description: "To understand more about how to use the convertor document, please check the `README` sheet",
}