module.exports = {
  /* Translated by:
   * Katsumi#8463 (first draft)
   */
  makerUserId:"358320066770501632",
  discordEmbedLengthLimit: 10,
  contentsName: "Contenu", // Name of field
  contentsNameSelection: "\uD83D\uDD33",
  contentsNameDeselection: "▫️",

  displayAll: "Tout",
  displayNone: "Aucun",
  displayTotal: "Total",
  displayGrandTotal: "Grand Total",
  displayAverageShorthand: "moy.",
  displayOtherItems: "Autres",
  displayBannerName: {
    "Character Event Banner": "Vœux événements de personnage",
    "Weapon Event Banner": "Vœux événements d'arme",
    "Permanent Banner": "Vœux permanents",
    "Novice Banner": "Vœux des débutants",
  },
  displayItemType: {
    "Character": "Personnage",
    "Weapon": "Arme",
  },
  languageList: {
    "English": "English",
    "ChineseSimplified": "Chinese Simplified",
    "ChineseTraditional": "Chinese Traditional",
    "French": "French",
    "German": "German",
    "Portuguese": "Portuguese",
    "Spanish": "Spanish",
    "Indonesian": "Indonesian",
    "Japanese": "Japanese",
    "Korean": "Korean",
    "Russian": "Russian",
    "Thai": "Thai",
    "Vietnamese": "Vietnamese"
  },
  rarity5StarEmoji: "⋆⋆⋆⋆⋆",
  rarity5StarName: "5 Étoiles",
  rarity4StarEmoji: "⋆⋆⋆⋆",
  rarity4StarName: "4 Étoiles",
  rarity3StarEmoji: "⋆⋆⋆",
  rarity3StarName: "3 Étoiles",
  refreshName: "Recharger",
  refreshEmoji: "🔄",
  statusSuccessName: "Succès",
  statusSuccessEmoji: "✅",
  statusErrorName: "Erreur",
  statusErrorEmoji: "❌",
  statusLoadingName: "Chargement",
  statusLoadingEmoji: "📂",
  statusCheckingName: "Vérification",
  statusCheckingEmoji: "⏳",
  statusProcessingName: "Traitement..",
  statusProcessingEmoji: "⏳",
  statusLoadedEmoji: "✅",
  statusLoadedName: "Chargée",
  statusLoadingEmoji: "⏳",
  statusLoadingName: "En cours de chargement",
  statusLoadEmoji: "❌",
  statusLoadName: "Pas chargé",

  urlImageError: "https://cdn.discordapp.com/attachments/814486266618970162/940599883658842122/error_1.png",
  urlImage5Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801560898850907/Final_5_Star.png",
  urlImage4Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801559669923940/Final_4_Star.png",
  urlImageTally: "https://cdn.discordapp.com/attachments/814486266618970162/859426718754275399/Wish-Tally---Community.png",
  urlExportConvertor: "https://docs.google.com/spreadsheets/d/1lXGo_pKxKmTzd9pg1b1gr6Fa-zfcM2ZQd0EnFfzg8Dk/edit",
  urlDiscordInvite: "https://discord.gg/CKuJSbtndV",
  urlGoogleWishTallyAddon: "https://workspace.google.com/marketplace/app/wish_tally/791037722195",
  urlGoogleSheet: "https://docs.google.com/spreadsheets/u/0/",
  // output message
  replaceCodeURL: "[URL]",
  replaceCodeTitle: "[TITLE]",
  replaceCodeProjectName: "[PROJECT_NAME]",
  replaceCodeFileType: "[FILE_TYPE]",
  replaceCodeStatus: "[STATUS]",
  replaceCodeRank: "[RANK]",
  replaceCodeCommandName: "[COMMAND_NAME]",
  replaceCodeEmoji: "[EMOJI]",
  replaceCodeStatusEmoji: "[EMOJI_STATUS]",
  replaceCodeAccountId: "[ACCOUNT_ID]",
  replaceCodeAccountsMax: "[ACCOUNTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeCommandDescription: "[COMMAND_DESCRIPTION]",
  replaceCodeLanguage: "[LANGUAGE]",
  replaceCodeParameter: "[PARAMETER]",
  replaceCodeDate: "[DATE]",
  replaceCodeDocumentVersion: "[DOCUMENT_VERSION]",
  replaceCodeGenshinVersion: "[GENSHIN_VERSION]",
  replaceCodeAttemptIndex: "[ATTEMPTS_INDEX]",
  replaceCodeAttemptMax: "[ATTEMPTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeValue:"[VALUE]",
  replaceCodePercentage:"[PERCENTAGE]",
  outputContent: "[COMMAND_NAME]|[EMOJI_STATUS]|For <@[USER_ID]> |[LANGUAGE]|[PARAMETER]|[COMMAND_DESCRIPTION] [DATE]",

  latestVersionCustomId: "[LOAD_LATEST_VERSION]",
  latestVersionName: "Version plus Récent",
  latestVersionEmoji: "🔎",
  latestVersionTitle: "[EMOJI] Genshin Impact Version [GENSHIN_VERSION]",
  // ping Command
  replaceCodeBotName: "[BOT_NAME]",
  pingMessage: ":wave: [BOT_NAME] Je suis encore en vie",
  // last-update Command
  lastUpdateMessageError: "Veuillez attendre le chargement de la feuille de Cache de la Communauté, état: [STATUS]",
  lastUpdateMessageException: "Erreur impossible de charger les données du Communauté Cache, état: [STATUS]",
  lastUpdateName: "Dernière MAJ",
  lastUpdateTitle: "Résumé de la Dernière MAJ du Document de la Communauté",
  lastUpdateEmoji: "⏲️",
  lastUpdateCustomId: "[LOAD_LAST_UPDATE]",
  lastUpdateDocumentTitle: "Communauté V[DOCUMENT_VERSION].X",

  lastUpdateStatusCommunityAccounts: "Document des Comptes de la  Communauté",
  lastUpdateStatusLanguagePadding: 18,
  lastUpdateStatusDocumentPadding: 16,
  lastUpdateStatusDocument: "DOCUMENT CHARGÉ",
  lastUpdateStatusDocumentAccount: "ACTUALISATION DES COMPTES",
  lastUpdateStatusDocumentCache: "RAFRAÎCHISSEMENT DU CACHE",
  lastUpdateStatusDocumentWishes: "RAFRAÎCHISSEMENT DE LA BANNIÈRE",
  lastUpdateStatusCommunityPadding: 15,
  lastUpdateStatusItemsByBanner: "ÉLÉMENTS PAR BANNIÈRE",
  lastUpdateStatusAccounts: "COMPTES",
  lastUpdateStatusCharacterBannerPity: "PITY",
  lastUpdateStatusDatePadding: 5,
  lastUpdateStatusStartDate: "DÉBUT",
  lastUpdateStatusEndDate: "FIN",
  lastUpdateStatusSummaryPadding: 14,
  lastUpdateStatusDuration: "DURÉE",
  lastUpdateStatusAttempts: "TENTATIVES",
  lastUpdateStatusMaxAccounts: "MAX COMPTES",
  lastUpdateStatusTotalWishes: "TOTAUX DES SOUHAITS",
  lastUpdateStatusCurrentUpdates: "VÉRIFICATION DE COMPTE",
  lastUpdateStatusHour: "heure",
  lastUpdateStatusHours: "heures",
  lastUpdateStatusAnd: "et",
  lastUpdateStatusMinute: "minute",
  lastUpdateStatusMinutes: "minutes",
  lastUpdateStatusAgo: "qu'il y a MAJ",
  /*
   * account Command
   */
  accountEmoji: "🔑",
  accountCustomId: "[LOAD_ACCOUNT]",
  accountName: "Compte",
  accountTitle: "[EMOJI] Compte",
  accountDescriptionFound: "Merci de contribuer à la Communauté Wish Tally. Il existe actuellement des données de [ACCOUNTS_MAX] comptes.\n\nVoici les options qui vous sont exclusives.",
  accountDescriptionNotFound: "Désolé, nous ne pouvons pas trouver votre compte Wish Tally, il y a [ACCOUNTS_MAX] comptes disponibles mais aucun n'est lié à votre compte Discord.\n\nVeuillez visiter la page d'aide pour savoir comment contribuer à la Communauté Wish Tally.\n\nSi vous avez récemment partagé votre compte sur ModMail, vous devez attendre que le personnel vérifie votre document.",
  accountDescriptionNotLoadedAccount: "Le Bot a récemment vidé le cache, il rechargera bientôt les comptes. Pour l'instant, les boutons sont tous activés, mais ces commandes nécessitent toujours un lien avec votre compte Wish Tally.",
  accountDescriptionLayout: "\n> [EMOJI][COMMAND_NAME] - [COMMAND_DESCRIPTION]",
  accountDescriptionRank: "Affichez le total de vos Vœux entre chaque Document de la Communauté et affichez votre rang moyen de pity.",
  accountDescriptionWish: "Affichez votre contribution de Vœux par rang, utile pour savoir quelle Version de Genshin était populaire parmi la communauté.",
  accountDescriptionPity: "Extrait votre dernière pity de votre document, pour montrer aux gens vos Vœux sans avoir besoin de prendre une capture d'écran.",
  accountDescriptionRate: "Affichez tous les taux de victoire pour les personnages à durée limitée dans les  `Bannières d'Événement de Personnage`.",
  /*
   * rank Command
   */
  rankEmoji: "🏆",
  rankCommunityEmoji: "🌎",
  rankCustomId: "[LOAD_RANK]",
  rankName: "Rang",
  rankAccountTitle: "Résumé des Comptes",
  rankTitle: "Résumé des Rangs",
  rankDescription: "Le Rang Personnel est votre classement en utilisant les données de votre document Wish Tally, le Rang Communautaire est la moyenne de tous les comptes, ce qui signifie que plus le nombre est bas, meilleur est votre classement.",
  rankCommunityTitle: "[EMOJI] Rang Communautaire",
  rankPersonalTitle: "[EMOJI] Rang Personnel",
  rankNoWishes: "Aucun Vœux effectuée lors de cette version.",
  /*
   * rank-wish Command
   */
  rankWishEmoji: "✨",
  rankWishCustomId: "[LOAD_RANK_WISH]",
  rankWishName: "Vœux",
  rankWishLimit: 15,
  rankWishGenshinVersionLimit: 5,
  rankWishGenshinVersionSameLimit: 2,
  rankWishLimitPadding: 2,
  rankWishSameTotalLimit: 3,
  rankWishSameTotalMessage: "__[STATUS] Comptes masqués de rang [RANK]__",
  rankWishTitle: "Rang par Vœux",
  rankWishNotReadyMessage: "Les données des Vœux par compte n'ont pas été chargées, veuillez réessayer.\n[STATUS]",
  rankWishLoadedMessage: "Rang par Vœux a été chargé avec succès",
  rankWishYouEmoji: "👈",
  rankWishRarity4StarEmoji: "4⭐",
  rankWishRarity5StarEmoji: "5⭐",
  rankWishSelectVersionDefaultPlaceholderForAll: "Toutes les Données de la Communauté",
  rankWishRankTitle: "Wish Tally Communauté V",
  rankWishRankGenshinTitle: "Genshin Version V",
  rankWishDocumentTitle: "Wish Tally Communauté V[DOCUMENT_VERSION].X",
  rankWishSelectVersionAllId: "[SELECT_RANK_WISH_VERSION_ALL]",
  rankWishSelectBannerIndexId: "[SELECT_RANK_WISH_BANNER_INDEX]",
  rankWishSelectVersionIndexId: "[SELECT_RANK_WISH_VERSION_INDEX]",
  rankWishMessageSuccessSelect: "Naviguer entre les bannières",
  rankWishMessageError: "Erreur rencontrée, réessayez une autre fois",

  checkCommunityAccountMessageError: "Veuillez attendre que la feuille des Comptes de la Communauté se charge, statut: [STATUS]",
  // finding account only show for error
  findingAccountName: "Cherchant Compte",
  findingAccountEmoji: "🔎",
  findingAccountMessageNotFound: "Erreur! Impossible de trouver les données de détails de votre compte à partir du Comptes de la Communauté\nSi vous n'avez pas rejoint la communauté, accédez à la page d'Aide pour savoir comment partager votre Document Wish Tally, si vous l'avez récemment fait, veuillez attendre que la Communauté se MAJ.",
  findingAccountMessageException: "Erreur! Impossible d'extraire les données du Document de la Communauté [DOCUMENT_VERSION].",
  findingAccountMessageError: "Erreur! Impossible de trouver la feuille des Comptes de la Communauté",

  displayRankMessageError: "Erreur! Impossible de trouver le Document de la Communauté [DOCUMENT_VERSION].",
  displayRankMessageNotFound: "Document de la Communauté [DOCUMENT_VERSION], n'a pas encore les détails de votre compte. La position de votre compte est [ACCOUNT_ID] alors qu'il y a [ACCOUNTS_MAX] comptes disponibles, veuillez attendre que la Communauté se mette à jour.",
  displayRankMessageException: "Erreur! Impossible d'extraire les données de la Communauté ",
  /*
   * pity Command
   */
  pityEmoji: "🧮",
  pityCustomId: "[LOAD_PITY]",
  pityName: "Pity",
  pityMessageError: "Erreur lors du chargement de votre document",
  pityMessageLoading: "Chargement du document tentative [ATTEMPTS_INDEX]/[ATTEMPTS_MAX].",
  pityMessageUnableLoad: "Erreur lors du chargement de votre document, réessayez plus tard.",
  pityMessageUnableFind: "Erreur impossible de trouver la feuille `Pity Checker` dans le document.",
  pityMessageLoadingPity: "Chargement des données de la feuille `Pity Checker tentative [ATTEMPTS_INDEX]/[ATTEMPTS_MAX].",
  pityMessageUnablePityExtract: "Erreur d'extraction de la feuille `Pity Checker` a totalement échoué, réessayez plus tard.",
  pityMessagePitySheetOld: "Votre feuille 'Pity Checker' n'est pas à jour, veuillez vérifier <#836651770100842576>.",
  pityMessagePitySheetSuccess: "Afficher la pity de votre document",
  pityCurrentWishNumber: "Numéro de Vœux Actuel",
  pityBackCustomId: "[LOAD_PITY_BACK]",
  pityNextCustomId: "[LOAD_PITY_NEXT]",
  pityBackEmoji: "⭐", // Back
  pityBackTitle: "⭐⭐⭐⭐⭐", // Back
  pityBackNoEarned: "⭐⭐⭐⭐⭐ - Aucun 5 Étoiles trouvé", // Back
  pityBackName: "5 Étoiles", // Back
  pityNextEmoji: "⭐", // Next
  pityNextTitle: "⭐⭐⭐⭐", // Next
  pityNextNoEarned: "⭐⭐⭐⭐ - Aucun 4 Étoiles trouvé", // Next
  pityNextName: "4 Étoiles", // Next
  /*
   * rate Command
   */
  rateEmoji: "🎯",
  rateCustomId: "[LOAD_RATE]",
  rateVersionCustomId: "[LOAD_RATE_VERSION]",
  rateName: "Taux",
  rateTitle: "[EMOJI] Taux",
  rateDescriptionSelection: "**Key**\n👎 - Impossible d'obtenir le caractère limité\n✌️ - Gagné 50/50\n👍 - Gagné en utilisant la pity précédente\n🙌 - Pity utilisé sur la bannière actuelle\n~~Choisissez la version du document que vous souhaitez voir plus en détail~~ Bientôt.",
  rateMessageError: "Erreur rencontrée lors du chargement des données de la Bannière de Personnage, réessayez une autre fois",
  rateNotReadyMessage: "La Pity de la Bannière de Personnage est toujours en cours de chargement, veuillez réessayer.\n[STATUS]",
  rateLoadedMessage: "Taux a été chargé avec succès",
  rateMenuSelectDocumentVersionPlaceholder: "Sélectionnez les données de la Wish Tally Communauté",
  rateMenuSelectDocumentVersionCustomId: "[SELECT_RATE_MENU_VERSION]",
  rateMenuSelectDocumentVersionSelection: "Wish Tally Communauté V[DOCUMENT_VERSION].X",
  rateBannerDisplayLayout: "\n**Version [GENSHIN_VERSION]**",
  rateInnerBannerDisplayLayout: "\n__[TITLE]__",
  rateItemDisplayLayout: "\n> [TITLE]",
  rateFirstBanner: "Première Bannière",
  rateSecondBanner: "Deuxième Bannière",
  rateThirdBanner: "Troisième Bannière",
  rateFourthBanner: "Quatrième Bannière",
  rateFifthBanner: "Cinquième Bannière",
  rateEmptyTotal: "Aucun gagné",
  rateTotalTitle: "Total",
  rateResultLayout: "`[TITLE] [VALUE]`",
  rateTotalMaxPadding: 4,
  ratePercentageMaxPadding: 3,
  rateWinEmoji: "✅",
  rateWinName: "", // Not in use
  rateLoseEmoji: "❌",
  rateLoseName: "", // Not in use

  rateFailedToGetEmoji: "👎",
  rateFailedToGetName: "Échoué",
  rateFailedToGetDetailed: "N'ai pas obtenu le caractère limité",
  rateWonFiftyFiftyEmoji:"✌️",
  rateWonFiftyFiftyName:"Gagné 50/50",
  rateWonFiftyFiftyDetailed:"Gagné le 50/50",
  rateUsedPityEmoji: "👍",
  rateUsedPityName: "Pity Utilisé",
  rateUsedPityDetailed: "Gagné en utilisant la pity précédente",
  rateSkippedEmoji: "👉", // Not in use
  rateSkippedName: "Sauté", // Not in use
  rateSkippedDetailed: "Aucune tentative de 5 Étoiles",
  rateSecondAttemptEmoji: "🙌",
  rateSecondAttemptName: "Usagé Pity Actuel",
  rateSecondAttemptDetailed: "Pity utilisé sur la bannière actuelle",
  rateResultLeftPercentageLayout: "`[EMOJI][VALUE]|[PERCENTAGE]%`",
  rateResultCenterPercentageLayout: "▰",
  rateResultRightPercentageLayout: "`%[PERCENTAGE]|[VALUE][EMOJI]`",
  rateResultPercentageCovered: "▰",
  rateResultPercentageUncovered: "▱",

  languageSelectByNameCustomId: "[SELECT_LANGUAGE_NAME]",
  /*
   * tally Command
   */
  tallyEmoji: "\uD83E\uDEA7",
  tallyCustomId: "[LOAD_TALLY]",
  botEmoji: "<:wish_tally:1015215165500825611>",
  tallyName: "Menu",
  tallyTitle: "[EMOJI] Wish Tally Bot",
  tallyDescription: "**[EMOJI] Bienvenue dans le menu Wish Tally**\n__Le Bot est géré par <@[USER_ID]>__",
  tallyDescriptionBot: "Utilisez les boutons ci-dessous pour contrôler le [EMOJI] Wish Tally bot.",
  tallyDescriptionHelp: "Seules les données de la Wish Tally Communauté sont affichées ici, consultez la [EMOJI] Page d'Aidee pour vous impliquer. \n\n**Veuillez noter** que __seule la personne qui a demandé le bot peut contrôler le bot__.",
  /*
   * report-m[DOCUMENT VERSION] Back Command
   */
  reportDocumentEmoji: "\uD83D\uDCD4",
  reportDocumentCustomId: "[LOAD_COMMUNITY_VERSION]",
  reportDocumentName: "Document",
  /*
   * report-m Command Load all doc
   */
  reportMenuEmoji: "<:wish_tally_community:1015216582231871611>",
  reportMenuCustomId: "[LOAD_COMMUNITY]",
  reportMenuName: "Communauté",
  reportMenuResetCustomId: "[LOAD_COMMUNITY_RESET]",
  reportMenuResetEmoji: "🗑️",
  reportMenuResetName: "Réinitialiser le filtre",
  reportMenuMessageError: "Impossible de charger le Document de la Communauté pour la Version `[DOCUMENT_VERSION]` n'existe peut-être pas encore?",
  reportMenuMessageErrorLoading: "Document de la Communauté pour la Version `[DOCUMENT_VERSION]` n'a pas encore été chargé.",
  reportMenuMessageException: "Erreur rencontrée impossible de charger le rapport du Document de la Communauté Version `[DOCUMENT_VERSION]`, veuillez réessayer?",
  reportMenuMessageNoData: "Aucune donnée à afficher pour le chargement de la version du Document de la Communauté `[DOCUMENT_VERSION]`, veuillez réessayer?",
  reportMenuMessageFound: "Affichant Document de la Communauté  `[DOCUMENT_VERSION]`",
  reportMenuDefaultPlaceholderForAll: "Toutes les Données de la Communauté",
  reportMenuSelectCustomId: "[SELECT_REPORT_MENU_VERSION]",
  reportMenuSelectAllId: "[SELECT_REPORT_MENU_ALL]",
  reportMenuSelectGensionVersionCustomId: "[SELECT_GENSHIN_VERSION]",
  reportMenuSelectGenshinVersionPlaceholder: "Sélectionner Genshin Impact Version",
  reportMenuSelectGensionVersionName: "Genshin Impact V[GENSHIN_VERSION]",
  reportMenuSelectIndexCustomId: "[SELECT_REPORT_MENU_INDEX]",
  reportMenuDocumentTitle: "Wish Tally Communauté V[DOCUMENT_VERSION].X",
  reportMenuDocumentSelectionTitle: "Wish Tally Communauté V[DOCUMENT_VERSION]", // Wish Tally Communauté V2.0 - 2.6
  reportMenuMessageSuccess: "Affichant menu du rapport",
  /*
   * Select Menu default error message, will display refresh name and emoji for [COMMAND_DESCRIPTION]
   */
  selectMenuMessageCacheError: "Impossible de basculer entre les messages, reprenez sur le dernier message ou utiliser [COMMAND_DESCRIPTION].",
  selectMenuMessageCacheRestarted: "Le bot a redémarré, impossible de basculer entre les pages, utiliser [COMMAND_DESCRIPTION].",
  /*
   * report-v[GENSHIN_VERSION] Command
   * Show specific Genshin Version, with all banners
   */
  reportEmoji: "\uD83D\uDCD4",
  reportCustomId: "[LOAD_REPORT_VERSION]",
  reportName: "Rapport",
  reportMessageError: "Impossible de charger le Document de la Communauté pour la Version [GENSHIN_VERSION] dans le 'v[DOCUMENT_VERSION]' n'existe peut-être pas encore?",
  reportMessageException: "Le document v[DOCUMENT_VERSION] a été chargé mais la version [GENSHIN_VERSION] a rencontré une erreur, veuillez réessayer",
  reportMessageUnableFindVersion: "Le document v[DOCUMENT_VERSION] a été chargé mais la version [GENSHIN_VERSION] n'existe peut-être pas encore, veuillez réessayer",
  reportMessageNoWishes: "Document v[DOCUMENT_VERSION] chargé, version [GENSHIN_VERSION] trouvée mais aucun vœux disponible, veuillez réessayer",
  reportMessageFound: "Données chargées pour la version [GENSHIN_VERSION]",
  reportSelectCustomId: "[SELECT_REPORT_VERSION]",
  reportSelectIndexCustomId: "[SELECT_REPORT_INDEX]",
  reportMessageSuccess: "Affichant rapport",
  /*
   * help Command
   * Homepage for help, will show all the steps
   */
  helpEmoji: "❓",
  helpCustomId: "[LOAD_HELP]",
  helpName: "Aide",
  helpTitle: "[EMOJI] Page d'Aide",
  googleAddonEmoji: "",
  googleAddonName: "Google Addon",
  discordServerEmoji: "",
  discordServerName: "Rejoindre le Serveur",
  helpStepsDescriptionLayout: "\n> [EMOJI][TITLE]",
  helpDescription: "En utilisant les réactions ci-dessous, chargez l'aide correspondante.\n\nWish Tally est un module Google Sheet qui est utilisé pour garder une trace de vos vœux, cela est nécessaire pour pouvoir partager avec la Wish Tally Communauté.",
  helpStep1Title: "Étape 1 - [EMOJI]",
  helpStep1Description: "Comment Obtenir Wish Tally",
  helpStep2Title: "Étape 2 - [EMOJI]",
  helpStep2Description: "Comment Importer des Vœux",
  helpStep3Title: "Étape 3 - [EMOJI]",
  helpStep3Description: "Comment Partager Wish Tally",
  helpCommandDescription: "Raccourci pour afficher les données sans naviguer à partir de la [EMOJI] Liste de Commandes",
  /*
   * help-command Command
   * List all the bot commands, useful for directly going to a specific page
   */
  helpCommandEmoji: "⌨️",
  helpCommandName: "Liste de Commandes",
  helpCommandTitle: "[EMOJI] Liste de Commandes",
  helpCommandCustomId: "[LOAD_HELP_COMMAND]",
  helpCommandDescription: "Raccourci dans la navigation avec les commandes",
  helpCommandDescriptionTally: "Afficher le menu principal",

  helpCommandMessageDisplay: "\n`[COMMAND_NAME]`\n> [COMMAND_DESCRIPTION]",

  helpCommandTitleHelp: "[EMOJI] Section d'Aide",
  helpCommandDescriptionHelp: "Menu d'Aide",
  helpCommandDescriptionHelpAddon: "Obtenir Wish Tally Addon",
  helpCommandDescriptionHelpImport: "Options d'Importation",
  helpCommandDescriptionHelpImportAuto: "Importation Automatique",
  helpCommandDescriptionHelpImportManual: "Importation Manuelle",
  helpCommandDescriptionHelpImportExport: "Exportation",
  helpCommandDescriptionHelpShare: "Partager Wish Tally",

  helpCommandTitleBotStat: "[EMOJI] Information du Bot",
  helpCommandDescriptionHelpLastUpdate: "Afficher la dernière mise à jour pour le chargement des données de la Communauté, car cela se fait selon un calendrier",

  helpCommandTitleData: "[EMOJI] Section des Données",
  helpCommandDescriptionReportMenu: "Affichez le résumé de tous les Documents de la Communauté",
  helpCommandDescriptionReportMenuSelection: "Sélectionnez un document spécifique pour le rapport, par exemple `!wish report-m2` pour v2.X document de la communauté",
  helpCommandDescriptionReport: "Générer un rapport sur une version spécifique de Genshin Impact, par exemple `!wish report-v2.4`",

  helpCommandTitleContributors: "[EMOJI] Compte",
  helpCommandDescriptionsContributor: "Uniquement pour les personnes qui ont partagé leur Wish Tally",
  helpCommandDescriptionRankWish: "Comparez votre nombre de 5 Étoiles avec la communauté",
  helpCommandDescriptionRank: "Affichez le classement moyen au sein de la communauté",
  helpCommandDescriptionPity: "Montrez votre Pity de Pity Checker",
  helpCommandDescriptionAccount: "Options de Menu pour les contributeurs de Wish Tally",
  helpCommandDescriptionRate: "Résumé du taux de réussite de toutes les bannières",



  // help-share Command
  helpShareEmoji: "🔓",
  helpShareCustomId: "[LOAD_HELP_SHARE]",
  helpShareName: "Partager Wish Tally",
  helpShareTitle: "[EMOJI] Comment Partager Wish Tally",

  helpShareMessageDescription: "Vous devez rejoindre le serveur Wish Tally Discord pour envoyer votre lien de partage.\n<[URL]>",
  helpShareMessage2Title: "Fournir un Lien de Partage",
  helpShareMessage2Description: "Allez dans le menu de la barre d'outils, `Fichier` puis `Partager`",
  helpShareMessage3Title: "EModifier l'Autorisation",
  helpShareMessage3Description: "Modifiez les restrictions de partage en cliquant sur `Replamcer par Tous les utilisateurs disposant du lien`",
  helpShareMessage4Title: "Tous les utilisateurs disposant du lien",
  helpShareMessage4Description: "Verifier que 3a est définie en tant que `Lecteur`, car mon script a juste besoin d'une autorisation pour voir la feuille.\nCliquez sur `Copier le lien` 3b pour me fournir le lien vers votre feuille Wish Tally.\nPour confirmer les modifications, cliquez sur `Terminé` 3c",
  helpShareMessage5Title: "Envoyez ModMail un message direct",
  helpShareMessage5Description: "Envoyez votre lien de partage au BOT ModMail",
  helpShareMessage6Title: "Choisissez le Serveur Discord",
  helpShareMessage6Description: "Dites à ModMail que vous souhaitez envoyer un message à `Wish Tally - Genshin Impact Pity Tracker`. Cliquez sur le bon numéro....",
  helpShareMessage7Title: "Message de confirmation",
  helpShareMessage7Description: "Vous devriez recevoir un message de confirmation de ModMail, le personnel vous aidera à partir de là.",
  /*
   * help-addon Command
   */
  helpAddonEmoji: "📝",
  helpAddonCustomId: "[LOAD_HELP_ADDON]",
  helpAddonName: "Obtenir Wish Tally",
  helpAddonTitle: "[EMOJI] Comment obtenir Wish Tally",
  helpAddonMessageDescription: "**Wish Tally est un Add-On officiel de Google**\nAvec l'Add-on approuvé par Google, cette méthode ne sera demandée ** qu'une seule fois **, même si vous créez plusieurs nouvelles feuilles. Il n'y a pas non plus de gros message d'avertissement de Google lors de l'installation de ce module complémentaire.\n\n__Visitez ici pour installer l'Add-on__\n\n",
  helpAddonMessage2Title: "Installer l'Add-On",
  helpAddonMessage2Description: "Passez par la fenêtre contextuelle d'autorisation pour installer Wish Tally",
  helpAddonMessage3Title: "Créer une nouvelle Feuille de Calcul",
  helpAddonMessage3Description: "Une fois l'add-on installé, vous pouvez l'affecter à n'importe quel document de feuille de calcul. Créez simplement une nouvelle feuille de calcul à partir de <[URL]> ou de la barre d'outils `Fichier` -> `Noveau` -> `Gérer les modules complémentaires`",
  helpAddonMessage4Title: "Activation d'Add-on",
  helpAddonMessage4Description: "Pour fournir un accès complet au script, vous devez indiquer à Google d'utiliser l'add-on pour cette feuille de calcul nouvellement créée.\nAllez dans `Extensions` -> `Modules Complémentaires` -> `Manage add-ons`",
  helpAddonMessage5Title: "Activer Wish Tally",
  helpAddonMessage5Description: "Une fenêtre apparaîtra après avoir sélectionné gérer les modules complémentaires. Accédez aux 3 points, puis à `Utiliser dans ce document`  pour activer le Wish Tally add-on.",
  helpAddonMessage6Title: "Actualisez votre Page",
  helpAddonMessage6Description: "**IMPORTANT** - L'actualisation du document changera automatiquement les paramètres régionaux en `United Kingdom`, ceci est fait afin de permettre à la formule de fonctionner.\n\nUtilisez le bouton d'actualisation ou `F5` pour forcer la page à se recharger.",
  helpAddonMessage7Title: "Initialiser le document",
  helpAddonMessage7Description: "Utiliser la barre d'outils `Extensions` -> `Wish Tally` -> `Initialiser` pour commencer à charger toutes les feuilles requises pour Wish Tally.",
  /*
   * help-import Command
   */
  helpImportEmoji: "📥",
  helpImportCustomId: "[LOAD_HELP_IMPORT]",
  helpImportName: "Importer des Vœux",
  helpImportTitle: "[EMOJI] Comment Importer des Vœux",
  helpImportDescription: "Il existe plusieurs méthodes d'ajout de Vœux dans le document Wish Tally, pour éviter toute erreur humaine lors de la saisie des Vœux, vous devez effectuer une `Importation Automatique`.",
  helpImportDescriptionAutoTitle: "[EMOJI] Importation Automatique (Recommandée)",
  helpImportDescriptionAuto: "Vous oblige à vous connecter au jeu et à extraire l'URL lors de la visite de l'Historique des Vœux.",
  helpImportDescriptionManualTitle: "[EMOJI] Importation Manuelle",
  helpImportDescriptionManual: "Il suffit de `copier` et de `coller` les Vœux directement, sans avoir besoin d'utiliser l'API. Doit comprendre comment utiliser la colonne override sinon les vœux sont tous hors service, il existe des outils disponibles qui aident à simplifier cette méthode.",
  helpImportDescriptionExportTitle: "[EMOJI] Convertir le Fichier d'Exportation en Wish Tally",
  helpImportDescriptionExport: "Si vous avez une sauvegarde de vos Vœux à partir d'autres Wish Trackers, vous pouvez utiliser un convertisseur d'exportation.",
  /*
   * help-import-auto Command
   */
  helpImportAutoEmoji: "🖥️",
  helpImportAutoCustomId: "[LOAD_HELP_IMPORT_AUTO]",
  helpImportAutoName: "Importation Automatique",
  helpImportAutoTitle: "[EMOJI] Importation Automatique des Vœux",
  
  helpImportAutoMessageDescription: "Cela permet d'importer automatiquement les données de Vœux dans votre feuille Wish Tally à l'aide de l'API miHoYo.\n\nCela fonctionne en utilisant l'URL et en extrayant la clé. Avec la clé, il communiquera ensuite avec miHoYo directement en votre nom pour vérifier l'Historique de vos Vœux et stocker tous les nouveaux Vœux trouvés sur votre feuille Wish Tally. Vous n'aurez pas besoin de override manuellement les entrées, car cela se fait automatiquement pour vous.\n\nVous pouvez toujours utiliser la méthode copier-coller comme moyen plus sûr d'enregistrer l'historique des Vœux, mais si vous souhaitez utiliser cette option plus simple, vous pouvez suivre ces étapes :\n**Veuillez noter que tous les Vœux qui sont plus anciens/plus de 6 mois ne peuvent pas être récupérés de cette façon, vous devez les enregistrer avant qu'ils ne soient plus visibles.**",
  helpImportAutoMessage2Title: "PC Étape 1 - Générer l'URL",
  helpImportAutoMessage2Description: "Connectez-vous à Genshin Impact, ouvrez le menu Wish et visitez les détails de l'historique des Vœux (peu importe l'historique des bannières que vous affichez). Cela générera l'URL dans votre fichier log text Genshin Impact.",
  helpImportAutoMessage3Title: "Étape 2 - Trouver le log file",
  helpImportAutoMessage3Description: "Ouvrir le navigateur de fichiers dans Windows et rechercher le dossier d'installation de votre jeu pour trouver le fichier `data_2` sur \n`Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\Cache_Data\\`",
  helpImportAutoMessage4Title: "Étape 3 - Extraire l'URL",
  helpImportAutoMessage4Description: "Cliquer droit et `Ouvrir avec` le fichier de texte `data_2` , avec `Notepad`",
  helpImportAutoMessage5Title: "Étape 4 - Copier l'URL",
  helpImportAutoMessage5Description: "Près du bas du fichier texte, vous verrez l'URL commençant par:\n\n```https://hk4e-api-os.hoyoverse.com/............game_biz=h4e_global```\n\nMettre en surbrillance et copier l'intégralité du texte de l'URL",
  helpImportAutoMessage6Title: "Étape 5 - Commencer l'Importation Automatique",
  helpImportAutoMessage6Description: "Assurez-vous que l'option `Auto Import from miHoYo` est définie et cliquez sur l'icône d'importation pour commencer.",
  helpImportAutoMessage7Title: "Étape 6",
  helpImportAutoMessage7Description: "Collez l'URL dans la fenêtre contextuelle d'importation automatique, puis appuyez sur `OK`.",
  helpImportAutoMessage8Title: "Pour la Chine Serveur",
  helpImportAutoMessage8Description: "Changer le serveur en `China` dans la feuille `Settings`, en utilisant l'option dans B3. Avant de procéder à l'utilisation de l'importation automatique..",
  /*
   * help-import-manual Command
   */
  helpImportManualEmoji: "🖱️",
  helpImportManualCustomId: "[LOAD_HELP_IMPORT_MANUAL]",
  helpImportManualName: "Importation Manuelle",
  helpImportManualTitle: "[EMOJI] Importation Manuelle des Vœux",
  helpImportManualMessageDescription: "Dans Wish Tally, vous pouvez copier et coller manuellement l'historique de vos Vœux comme autre alternative à l'utilisation de l'importation automatique. Cette méthode ne nécessite pas d'outils supplémentaires, mais il est important d'utiliser la colonne de override pour 10 Vœux (même date et heure), afin de s'assurer que les Vœux sont enregistrés avec précision dans le bon ordre.",
  helpImportManualMessage2Title: "Étape 1 - Copier l'Historique des Vœux dans Wish Tally",
  helpImportManualMessage2Description: "Accédez au menu Wish et sélectionnez 'Historique' à l'aide des touches appropriées.\n\nEnsuite, sélectionnez les informations comme indiqué dans l'image et copiez-les à l'aide du raccourci `CTRL + C` (le clic droit est désactivé).",
  helpImportManualMessage3Title: "Étape 2",
  helpImportManualMessage3Description: "À partir du `Dashboard`, accédez à la page d'historique des vœux correspondante dans votre feuille de calcul.",
  helpImportManualMessage4Title: "Coller Valeurs",
  helpImportManualMessage4Description: "Ensuite, appuyez sur une cellule vide dans la colonne A, puis appuyez sur `CTRL + V` ou `CTRL + Shift + V` (Coller des valeurs uniquement)",
  helpImportManualMessage5Title: "Problèmes avec Coller",
  helpImportManualMessage5Description: "Si la valeur de collage ressemble à ceci, vous devrez éviter d'utiliser le menu d'option de clic droit lors du collage.",
  helpImportManualMessage6Title: "Étape 3 - Gestion des 10 Pulls à l'aide d'override (Très Important)",
  helpImportManualMessage6Description: "Tous les Vœux dans un multi de 10 auront le même horodatage et la même date. Étant donné que l'Historique des Vœux de Genshin est affiché du plus récent au plus ancien, nous pouvons supposer que la dernière entrée dans le 10 multi est le Vœu numéro 1.\n\nCopiez d'abord l'historique en utilisant la méthode indiquée précédemment, puis numérotez ces éléments dans l'ordre dans l'onglet Historique de votre feuille de calcul en suivant cette méthode.\n\nDans l'exemple suivant, le `Raven Bow` au bas de la liste serait le premier pull.",
  helpImportManualMessage7Title: "",
  helpImportManualMessage7Description: "Collez la valeur [CTRL+V] et attribuez l'override manuellement en tapant les numéros correspondants.",
  helpImportManualMessage8Title: "",
  helpImportManualMessage8Description: "Passez à la page suivante (par exemple, passez à la page 14 après 13) et faites la même chose pour les 10 multi restants.",
  helpImportManualMessage9Title: "Étape 4 - Trier les Vœux dans l'ordre",
  helpImportManualMessage9Description: "En raison de l'ordre de l'Historique des Vœux, la valeur collée doit être triée.\n\nAssurez-vous que tous les Vœux multiples ont des numéros d'override saisis, sinon le tri sera erroné.\n\nCliquez sur le bouton `SORT` à la haut de la feuille lorsque vous êtes prêt.\n\nLorsque le tri est appliqué, l'override triera automatiquement les Vœux multiples de 1 à 10 et les Vœux uniques par date et heure.",
  /*
   * help-import-export Command
   */
  helpImportExportEmoji: "⛏️",
  helpImportExportCustomId: "[LOAD_HELP_IMPORT_EXPORT]",
  // List of options
  helpImportExportMessageOptionLayout: "\n[PROJECT_NAME] `[FILE_TYPE]`- <[URL]>",
  exportOption1ProjectName: "Exportation de Genshin Wish",
  exportOption1FileType: "XLSX file",
  exportOption1URL: "https://github.com/biuuu/genshin-wish-export",
  exportOption2ProjectName: "Genshin Wishes",
  exportOption2FileType: "CSV file",
  exportOption2URL: "https://genshin-wishes.com",
  exportOption3ProjectName: "paimon.moe",
  exportOption3FileType: "XLSX file",
  exportOption3URL: "https://paimon.moe",

  helpImportExportName: "Importation par Exportation",
  helpImportExportTitle: "[EMOJI] Importation des Vœux par Exportation",
  helpImportExportMessageDescription: "Utilisez ce convertisseur des documents pour vous aider à convertir vos Vœux pour Wish Tally.\n<[URL]>\n\n**Fichiers d'Exportation pris en charge**",

  helpImportExportMessage2Title: "Faire une Copie de la Feuille de Calcul",
  helpImportExportMessage2Description: "Vous devez d'abord disposer d'un compte Google avant de pouvoir accéder à la feuille de calcul. Faites une copie de cette feuille de calcul dans votre Google Drive.\n<[URL]>\n\nDans la barre d'outils du menu `Fichier`, cliquez sur `Créer une copie`. Cela créera une copie de la feuille de calcul dans votre Google Drive, que vous pourrez ensuite modifier pour enregister votre propre Historique de Vœux.\n\nUne fenêtre contextuelle `Copier le document` apparaîtra, vous pouvez renommer le document dans la section `Nom`, en cliquant sur sur `OK` enregistrera une copie de Wish Tally Conversion dans votre Google Drive.",
  helpImportExportMessage3Title: "Vérifiez le README",
  helpImportExportMessage3Description: "Pour en savoir plus sur l'utilisation du convertisseur des documents, veuillez consulter la feuille `README`",
}