module.exports = {
  // Discord Emoji List
  // https://emzi0767.gl-pages.emzi0767.dev/discord-emoji/discordEmojiMap-canary.json
  makerUserId:"358320066770501632",
  discordEmbedLengthLimit: 10,
  contentsName: "Conteúdos", // Name of field
  contentsNameSelection: "\uD83D\uDD33",
  contentsNameDeselection: "▫️",

  displayAll: "Tudo",
  displayNone: "Nada",
  displayTotal: "Total",
  displayGrandTotal: "Total Geral",
  displayAverageShorthand: "média",
  displayOtherItems: "Outros",
  displayBannerName: {
    "Character Event Banner": "Oração de Evento de Personagem",
    "Weapon Event Banner": "Oração do Evento de Arma",
    "Permanent Banner": "Desejo Comum",
    "Novice Banner": "Desejos de Novato",
  },
  displayItemType: {
    "Character": "Personagem",
    "Weapon": "Arma",
  },
  
  rarity5StarEmoji: "⋆⋆⋆⋆⋆",
  rarity5StarName: "5 Estrelas",
  rarity4StarEmoji: "⋆⋆⋆⋆",
  rarity4StarName: "4 Estrelas",
  rarity3StarEmoji: "⋆⋆⋆",
  rarity3StarName: "3 Estrelas",
  refreshName: "Recarregar",
  refreshEmoji: "🔄",
  statusSuccessName: "Successo",
  statusSuccessEmoji: "✅",
  statusErrorName: "Erro",
  statusErrorEmoji: "❌",
  statusLoadingName: "Carregango",
  statusLoadingEmoji: "📂",
  statusCheckingName: "Verificando",
  statusCheckingEmoji: "⏳",
  statusProcessingName: "Processando..",
  statusProcessingEmoji: "⏳",
  statusLoadedEmoji: "✅",
  statusLoadedName: "Loaded",
  statusLoadingEmoji: "⏳",
  statusLoadingName: "A Carregar",
  statusLoadEmoji: "❌",
  statusLoadName: "Não Carregou",

  urlImageError: "https://cdn.discordapp.com/attachments/814486266618970162/940599883658842122/error_1.png",
  urlImage5Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801560898850907/Final_5_Star.png",
  urlImage4Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801559669923940/Final_4_Star.png",
  urlImageTally: "https://cdn.discordapp.com/attachments/814486266618970162/859426718754275399/Wish-Tally---Community.png",
  urlExportConvertor: "https://docs.google.com/spreadsheets/d/1lXGo_pKxKmTzd9pg1b1gr6Fa-zfcM2ZQd0EnFfzg8Dk/edit",
  urlDiscordInvite: "https://discord.gg/CKuJSbtndV",
  urlGoogleWishTallyAddon: "https://workspace.google.com/marketplace/app/wish_tally/791037722195",
  urlGoogleSheet: "https://docs.google.com/spreadsheets/u/0/",
  // output message
  replaceCodeURL: "[URL]",
  replaceCodeTitle: "[TITLE]",
  replaceCodeProjectName: "[PROJECT_NAME]",
  replaceCodeFileType: "[FILE_TYPE]",
  replaceCodeStatus: "[STATUS]",
  replaceCodeRank: "[RANK]",
  replaceCodeCommandName: "[COMMAND_NAME]",
  replaceCodeEmoji: "[EMOJI]",
  replaceCodeStatusEmoji: "[EMOJI_STATUS]",
  replaceCodeAccountId: "[ACCOUNT_ID]",
  replaceCodeAccountsMax: "[ACCOUNTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeCommandDescription: "[COMMAND_DESCRIPTION]",
  replaceCodeLanguage: "[LANGUAGE]",
  replaceCodeParameter: "[PARAMETER]",
  replaceCodeDate: "[DATE]",
  replaceCodeDocumentVersion: "[DOCUMENT_VERSION]",
  replaceCodeGenshinVersion: "[GENSHIN_VERSION]",
  replaceCodeAttemptIndex: "[ATTEMPTS_INDEX]",
  replaceCodeAttemptMax: "[ATTEMPTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeValue:"[VALUE]",
  replaceCodePercentage:"[PERCENTAGE]",
  outputContent: "[COMMAND_NAME]|[EMOJI_STATUS]|For <@[USER_ID]> |[LANGUAGE]|[PARAMETER]|[COMMAND_DESCRIPTION] [DATE]",

  latestVersionCustomId: "[LOAD_LATEST_VERSION]",
  latestVersionName: "Versão Mais Recente",
  latestVersionEmoji: "🔎",
  latestVersionTitle: "[EMOJI] Genshin Impact Versão [GENSHIN_VERSION]",
  // ping Command
  replaceCodeBotName: "[BOT_NAME]",
  pingMessage: ":wave: [BOT_NAME] Ainda estou a funcionar",
  // last-update Command
  lastUpdateMessageError: "Por favor aguarde que a página da Cache da Comunidade carregue, estado: [STATUS]",
  lastUpdateMessageException: "Erro incapaz de carregar os dados da Cache da Comunidade, estado: [STATUS]",
  lastUpdateName: "Última Atualização",
  lastUpdateTitle: "Sumário da Última Atualização do Documento da Comunidade",
  lastUpdateEmoji: "⏲️",
  lastUpdateCustomId: "[LOAD_LAST_UPDATE]",
  lastUpdateDocumentTitle: "Comunidade V[DOCUMENT_VERSION].X",

  lastUpdateStatusCommunityAccounts: "Documento de Contas da Comunidade",
  lastUpdateStatusLanguagePadding: 18,
  lastUpdateStatusDocumentPadding: 16,
  lastUpdateStatusDocument: "DOCUMENTO CARREGADO",
  lastUpdateStatusDocumentAccount: "ATUALIZAR CONTAS",
  lastUpdateStatusDocumentCache: "ATUALIZAR CACHE",
  lastUpdateStatusDocumentWishes: "ATUALIZAR BANNER",
  lastUpdateStatusCommunityPadding: 15,
  lastUpdateStatusItemsByBanner: "ITENS POR BANNER",
  lastUpdateStatusAccounts: "CONTAS",
  lastUpdateStatusCharacterBannerPity: "PIEDADE",
  lastUpdateStatusDatePadding: 5,
  lastUpdateStatusStartDate: "COMEÇO",
  lastUpdateStatusEndDate: "FIM",
  lastUpdateStatusSummaryPadding: 14,
  lastUpdateStatusDuration: "DURAÇÃO",
  lastUpdateStatusAttempts: "TENTATIVAS",
  lastUpdateStatusMaxAccounts: "TOTAL DE CONTAS",
  lastUpdateStatusTotalWishes: "TOTAL DE DESEJOS",
  lastUpdateStatusCurrentUpdates: "VERIFICANDO CONTA",
  lastUpdateStatusHour: "hora",
  lastUpdateStatusHours: "horas",
  lastUpdateStatusAnd: "e",
  lastUpdateStatusMinute: "minuto",
  lastUpdateStatusMinutes: "minutos",
  lastUpdateStatusAgo: "atrás",
  /*
   * account Command
   */
  accountEmoji: "🔑",
  accountCustomId: "[LOAD_ACCOUNT]",
  accountName: "Conta",
  accountTitle: "[EMOJI] Conta",
  accountDescriptionFound: "Obrigado por contribuir para a Comunidade Wish Tally, atualmente temos dados de [ACCOUNTS_MAX] contas.\n\nAqui estão as opções exclusivas para si.",
  accountDescriptionNotFound: "Desculpe, não conseguimos encontrar a sua conta Wish Tally, existem [ACCOUNTS_MAX] contas disponíveis mas nenhuma está associada à sua Conta no Discord.\n\nPor favor utilize a página de ajuda para descobrir como contribuir para a Comunidade Wish Tally.\n\nSe partilhou recentemente a sua conta através do ModMail, aguarde que a equipa verifique o seu documento.",
  accountDescriptionNotLoadedAccount: "O Bot limpou recentemente a cache, irá recarregar todas as contar brevemente. Por enquanto todos os botões estão ativos, mas estes comandos ainda requerem ligação à sua conta Wish Tally.",
  accountDescriptionLayout: "\n> [EMOJI][COMMAND_NAME] - [COMMAND_DESCRIPTION]",
  accountDescriptionRank: "Exibe as suas orações totais entre cada Documento da Comunidade e mostra o seu rank médio de piedade.",
  accountDescriptionWish: "Exibe a sua contribuição de orações por rank, útil para saber qual Versão do Genshin foi popular entre a comunidade.",
  accountDescriptionPity: "Extrai sua piedade mais recente do seu documento, para mostrar às pessoas as suas orações desejos sem a necessidade de tirar uma captura de tela.",
  accountDescriptionRate: "Mostrar todas as taxas de vitórias para personagens de tempo limitado em `Banners de Eventos de Personagens`.",
  /*
   * rank Command
   */
  rankEmoji: "🏆",
  rankCommunityEmoji: "🌎",
  rankCustomId: "[LOAD_RANK]",
  rankName: "Rank",
  rankAccountTitle: "Sumário de Conta",
  rankTitle: "Sumário de Rank",
  rankDescription: "O rank é a sua classificação usando os dados do seu documento Wish Tally, o rank da Comunidade é a média de todas as contas, o que significa que quanto menor o seu número, melhor é sua classificação.",
  rankCommunityTitle: "[EMOJI] Ranking da Comunidade",
  rankPersonalTitle: "[EMOJI] Ranking Pessoal",
  rankNoWishes: "Não foram realizadas orações nesta versão.",
  /*
   * rank-wish Command
   */
  rankWishEmoji: "✨",
  rankWishCustomId: "[LOAD_RANK_WISH]",
  rankWishName: "Oração",
  rankWishLimit: 15,
  rankWishGenshinVersionLimit: 5,
  rankWishGenshinVersionSameLimit: 2,
  rankWishLimitPadding: 2,
  rankWishSameTotalLimit: 3,
  rankWishSameTotalMessage: "__Ocultadas [STATUS] Contas cujo rank é [RANK]__",
  rankWishTitle: "Ranking de Orações",
  rankWishNotReadyMessage: "Dados de Orações por conta não carregados, por favor tente novamente.\n[STATUS]",
  rankWishLoadedMessage: "Rank por orações carregado com sucesso",
  rankWishYouEmoji: "👈",
  rankWishRarity4StarEmoji: "4⭐",
  rankWishRarity5StarEmoji: "5⭐",
  rankWishSelectVersionDefaultPlaceholderForAll: "Todos os Dados de Comunidade",
  rankWishRankTitle: "Wish Tally Comunidade V",
  rankWishRankGenshinTitle: "Genshin Versão V",
  rankWishDocumentTitle: "Wish Tally Comunidade V[DOCUMENT_VERSION].X",
  rankWishSelectVersionAllId: "[SELECT_RANK_WISH_VERSION_ALL]",
  rankWishSelectBannerIndexId: "[SELECT_RANK_WISH_BANNER_INDEX]",
  rankWishSelectVersionIndexId: "[SELECT_RANK_WISH_VERSION_INDEX]",
  rankWishMessageSuccessSelect: "Alternando entre banners",
  rankWishMessageError: "Erro encontrado, tente novamente noutra altura",

  checkCommunityAccountMessageError: "Por favor aguarde enquanto a página de Contas da Comunidade carrega, estado: [STATUS]",
  // finding account only show for error
  findingAccountName: "Procurando Conta",
  findingAccountEmoji: "🔎",
  findingAccountMessageNotFound: "Erro! Impossível de encontrar os dados da sua conta nas Contas da Comunidade\nSe ainda não se juntou à comunidade vá à página de Ajuda para descobrir como partilhar o seu Documento Wish Tally, se já o fez recentemente por favor aguarde que a Comunidade seja atualizada.",
  findingAccountMessageException: "Erro! Impossível de extrair os dados do Documento da Comunidade [DOCUMENT_VERSION].",
  findingAccountMessageError: "Erro! Impossível de encontrar a página Contas da Comunidade",

  displayRankMessageError: "Erro! Impossível de encontrar o Documento da Comunidade [DOCUMENT_VERSION].",
  displayRankMessageNotFound: "Documento da Comunidade [DOCUMENT_VERSION], ainda não tem os detalhes da sua conta. A posição da sua Conta é [ACCOUNT_ID] enquanto existem [ACCOUNTS_MAX] contas disponíveis, por favor aguarde que a Comunidade seja atualizada.",
  displayRankMessageException: "Erro! Impossível de extrair os dados da Comunidade ",
  /*
   * pity Command
   */
  pityEmoji: "🧮",
  pityCustomId: "[LOAD_PITY]",
  pityName: "Piedade",
  pityMessageError: "Erro ao carregar o seu documento",
  pityMessageLoading: "Carregando o documento, tentativa [ATTEMPTS_INDEX]/[ATTEMPTS_MAX].",
  pityMessageUnableLoad: "Erro, impossível carregar o seu documento, tente mais tarde.",
  pityMessageUnableFind: "Erro, impossível encontrar a página `Pity Checker` no seu documento.",
  pityMessageLoadingPity: "Carregango a página de dados `Pity Checker`, tentativa [ATTEMPTS_INDEX]/[ATTEMPTS_MAX].",
  pityMessageUnablePityExtract: "Erro, extração dos dados da página `Pity Checker` falhou po completo, tente novamente mais tarde.",
  pityMessagePitySheetOld: "A página 'Pity Checker' do seu Documento está desatualizada, verifique <#836651770100842576>.",
  pityMessagePitySheetSuccess: "Exibindo a piedade do seu documento",
  pityCurrentWishNumber: "Número de Oração atual",
  pityBackCustomId: "[LOAD_PITY_BACK]",
  pityNextCustomId: "[LOAD_PITY_NEXT]",
  pityBackEmoji: "⭐", // Back
  pityBackTitle: "⭐⭐⭐⭐⭐", // Back
  pityBackNoEarned: "⭐⭐⭐⭐⭐ - Nenhum item de 5 Estrelas encontrado", // Back
  pityBackName: "5 Estrelas", // Back
  pityNextEmoji: "⭐", // Next
  pityNextTitle: "⭐⭐⭐⭐", // Next
  pityNextNoEarned: "⭐⭐⭐⭐ - Nenhum item de 4 Estrelas encontrado", // Next
  pityNextName: "4 Estrelas", // Next
  /*
   * rate Command
   */
  rateEmoji: "🎯",
  rateCustomId: "[LOAD_RATE]",
  rateVersionCustomId: "[LOAD_RATE_VERSION]",
  rateName: "Drops",
  rateTitle: "[EMOJI] Drops",
  rateDescriptionSelection: "**Key**\n👎 - Não obteve a personagem promocional\n✌️ - Ganhou o 50/50\n👍 - Ganhou usando a piedade prévia\n🙌 - Usou a piedade na Banner atual\n~~Escolha qual versão do documento deseja ver em detalhe~~ Brevemente.",
  rateMessageError: "Erro encontrado ao carregar a Piedade da Banner do Evento de Persongens, tente novamente mais tarde",
  rateNotReadyMessage: "Piedade da Banner do Evento de Persongens ainda está a carregar, por favor tente novamente.\n[STATUS]",
  rateLoadedMessage: "Drops foi carregado com sucesso",
  rateMenuSelectDocumentVersionPlaceholder: "Seleccione Dados da Wish Tally Comunidade",
  rateMenuSelectDocumentVersionCustomId: "[SELECT_RATE_MENU_VERSION]",
  rateMenuSelectDocumentVersionSelection: "Wish Tally Comunidade V[DOCUMENT_VERSION].X",
  rateBannerDisplayLayout: "\n**Versão [GENSHIN_VERSION]**",
  rateInnerBannerDisplayLayout: "\n__[TITLE]__",
  rateItemDisplayLayout: "\n> [TITLE]",
  rateFirstBanner: "Primeira Banner",
  rateSecondBanner: "Segunda Banner",
  rateThirdBanner: "Terceira Banner",
  rateFourthBanner: "Quarta Banner",
  rateFifthBanner: "Quinta Banner",
  rateEmptyTotal: "Nada obtido",
  rateTotalTitle: "Total",
  rateResultLayout: "`[TITLE] [VALUE]`",
  rateTotalMaxPadding: 4,
  ratePercentageMaxPadding: 3,
  rateWinEmoji: "✅",
  rateWinName: "", // Not in use
  rateLoseEmoji: "❌",
  rateLoseName: "", // Not in use

  rateFailedToGetEmoji: "👎",
  rateFailedToGetName: "Falhou",
  rateFailedToGetDetailed: "Não conseguiu obter a personagem promocional",
  rateWonFiftyFiftyEmoji:"✌️",
  rateWonFiftyFiftyName:"Ganhou o 50/50",
  rateWonFiftyFiftyDetailed:"Ganhou o 50/50",
  rateUsedPityEmoji: "👍",
  rateUsedPityName: "Usou a Piedade",
  rateUsedPityDetailed: "Ganhou usando a piedade ganha previamente",
  rateSkippedEmoji: "👉", // Not in use
  rateSkippedName: "Passou", // Not in use
  rateSkippedDetailed: "Não tentou obter personagens de 5 Estrelas",
  rateSecondAttemptEmoji: "🙌",
  rateSecondAttemptName: "Usou a Piedade atual",
  rateSecondAttemptDetailed: "Usou a piedade na Banner atual",
  rateResultLeftPercentageLayout: "`[EMOJI][VALUE]|[PERCENTAGE]%`",
  rateResultCenterPercentageLayout: "▰",
  rateResultRightPercentageLayout: "`%[PERCENTAGE]|[VALUE][EMOJI]`",
  rateResultPercentageCovered: "▰",
  rateResultPercentageUncovered: "▱",

  languageSelectByNameCustomId: "[SELECT_LANGUAGE_NAME]",
  /*
   * tally Command
   */
  tallyEmoji: "\uD83E\uDEA7",
  tallyCustomId: "[LOAD_TALLY]",
  botEmoji: "<:wish_tally:1015215165500825611>",
  tallyName: "Menu",
  tallyTitle: "[EMOJI] Bot Wish Tally",
  tallyDescription: "**[EMOJI] Bem-vindo ao Menu da Wish Tally**\n__Bot is managed by <@[USER_ID]>__",
  tallyDescriptionBot: "Utilize os botões abaixo para controlar o [EMOJI] Wish Tally bot.",
  tallyDescriptionHelp: "Apenas pode ver aqui data da Comunidade da Wish Tally, veja a [EMOJI] Página de Ajuda para se juntar. \n\n**Atenção** que __apenas a pessoa que solicitou o bot o pode controlar__.",
  /*
   * report-m[DOCUMENT VERSION] Back Command
   */
  reportDocumentEmoji: "\uD83D\uDCD4",
  reportDocumentCustomId: "[LOAD_COMMUNITY_VERSION]",
  reportDocumentName: "Documento",
  /*
   * report-m Command Load all doc
   */
  reportMenuEmoji: "<:wish_tally_community:1015216582231871611>",
  reportMenuCustomId: "[LOAD_COMMUNITY]",
  reportMenuName: "Comunidade",
  reportMenuResetCustomId: "[LOAD_COMMUNITY_RESET]",
  reportMenuResetEmoji: "🗑️",
  reportMenuResetName: "Limpar Filtros",
  reportMenuMessageError: "Impossível de carregar o Documento da Comunidade para a Versão `[DOCUMENT_VERSION]` pode ainda não existir?",
  reportMenuMessageErrorLoading: "Documento da Comunidade para a Versão `[DOCUMENT_VERSION]` ainda não carregou.",
  reportMenuMessageException: "Erro encontrado, impossível carregar o relatório do Documento da Comunidade Versão `[DOCUMENT_VERSION]`, por favor tente novamente?",
  reportMenuMessageNoData: "Não há dados a serem exibidos por carregar o Documento da Comunidade Versão `[DOCUMENT_VERSION]`, por favor tente novamente?",
  reportMenuMessageFound: "Exibinto o Documento da Comunidade Versão `[DOCUMENT_VERSION]`",
  reportMenuDefaultPlaceholderForAll: "Todos os Dados da Comunidade",
  reportMenuSelectCustomId: "[SELECT_REPORT_MENU_VERSION]",
  reportMenuSelectAllId: "[SELECT_REPORT_MENU_ALL]",
  reportMenuSelectGensionVersionCustomId: "[SELECT_GENSHIN_VERSION]",
  reportMenuSelectGenshinVersionPlaceholder: "Seleccione a Versão do Genshin Impact",
  reportMenuSelectGensionVersionName: "Genshin Impact V[GENSHIN_VERSION]",
  reportMenuSelectIndexCustomId: "[SELECT_REPORT_MENU_INDEX]",
  reportMenuDocumentTitle: "Wish Tally Comunidade V[DOCUMENT_VERSION].X",
  reportMenuDocumentSelectionTitle: "Wish Tally Comunidade V[DOCUMENT_VERSION]", // Wish Tally Community V2.0 - 2.6
  reportMenuMessageSuccess: "Exibindo o menu de relatórios",
  /*
   * Select Menu default error message, will display refresh name and emoji for [COMMAND_DESCRIPTION]
   */
  selectMenuMessageCacheError: "Impossível de alternar entre mensagens, Cannot switch between message, retome na última mensagem ou utilize [COMMAND_DESCRIPTION].",
  selectMenuMessageCacheRestarted: "O Bot reiniciou, impossível de alternar entre páginas, utilize [COMMAND_DESCRIPTION].",
  /*
   * report-v[GENSHIN_VERSION] Command
   * Show specific Genshin Version, with all banners
   */
  reportEmoji: "\uD83D\uDCD4",
  reportCustomId: "[LOAD_REPORT_VERSION]",
  reportName: "Relatório",
  reportMessageError: "Impossível de carregar o Documento da Comunidade para a Versão [GENSHIN_VERSION] na 'v[DOCUMENT_VERSION]' pode ainda não existir?",
  reportMessageException: "Documento v[DOCUMENT_VERSION] carregado mas a versão [GENSHIN_VERSION] encontrou um erro, por favor tente novamente",
  reportMessageUnableFindVersion: "Documento v[DOCUMENT_VERSION] carregado mas a versão [GENSHIN_VERSION] parece ainda não existir, por favor tente novamente",
  reportMessageNoWishes: "Documento v[DOCUMENT_VERSION] carregado, versão [GENSHIN_VERSION] encontrada mas sem orações disponíveis, por favor tente novamente",
  reportMessageFound: "Dados para a versão [GENSHIN_VERSION] carregados",
  reportSelectCustomId: "[SELECT_REPORT_VERSION]",
  reportSelectIndexCustomId: "[SELECT_REPORT_INDEX]",
  reportMessageSuccess: "Exibindo o relatório",
  /*
   * help Command
   * Homepage for help, will show all the steps
   */
  helpEmoji: "❓",
  helpCustomId: "[LOAD_HELP]",
  helpName: "Ajuda",
  helpTitle: "[EMOJI] Página de Ajuda",
  googleAddonEmoji: "",
  googleAddonName: "Google Addon",
  discordServerEmoji: "",
  discordServerName: "Conecte-se ao Servidor",
  helpStepsDescriptionLayout: "\n> [EMOJI][TITLE]",
  helpDescription: "Utilize as reações abaixo para carregar a Ajuda necessária.\n\nA Wish Tally é um Addon para as Planilhas Google que é utilizado para registar as suas Orações, é necessário criar a sua própria planilha para a poder partilhar com a Comunidade Wish Tally.",
  helpStep1Title: "Passo 1 - [EMOJI]",
  helpStep1Description: "Como obter a Wish Tally",
  helpStep2Title: "Passo 2 - [EMOJI]",
  helpStep2Description: "Como importar Orações",
  helpStep3Title: "Passo 3 - [EMOJI]",
  helpStep3Description: "Como partilhar a sua Wish Tally",
  helpCommandDescription: "Atalho para exibir dados sem navegar através da [EMOJI] Lista de Comandos",
  /*
   * help-command Command
   * List all the bot commands, useful for directly going to a specific page
   */
  helpCommandEmoji: "⌨️",
  helpCommandName: "Comandos",
  helpCommandTitle: "[EMOJI] Lista de Comandos",
  helpCommandCustomId: "[LOAD_HELP_COMMAND]",
  helpCommandDescription: "Atalho para navegar os comandos",
  helpCommandDescriptionTally: "Abrir o menu principal",

  helpCommandMessageDisplay: "\n`[COMMAND_NAME]`\n> [COMMAND_DESCRIPTION]",

  helpCommandTitleHelp: "[EMOJI] Secção de Ajuda",
  helpCommandDescriptionHelp: "Menu de Ajuda",
  helpCommandDescriptionHelpAddon: "Obter o Addon Wish Tally",
  helpCommandDescriptionHelpImport: "Opções de Importação",
  helpCommandDescriptionHelpImportAuto: "Auto Importação",
  helpCommandDescriptionHelpImportManual: "Manual",
  helpCommandDescriptionHelpImportExport: "Exportação",
  helpCommandDescriptionHelpShare: "Partilhar a Wish Tally",

  helpCommandTitleBotStat: "[EMOJI] Informação do Bot",
  helpCommandDescriptionHelpLastUpdate: "Exibe a última atualização dos dados introduzidos na Comunidade, um vez que a atualização é efectuada de acordo com uma programação horária.",

  helpCommandTitleData: "[EMOJI] Secção dos Dados",
  helpCommandDescriptionReportMenu: "Exibve o sumário de todos os documentos da comunidade",
  helpCommandDescriptionReportMenuSelection: "Selecciona o relatório de um documento específico, ex. `!wish report-m2` para o documento de comunidade v2.X",
  helpCommandDescriptionReport: "Cria o relatório de uma versão específica do Genshin Impact, ex. `!wish report-v2.4`",

  helpCommandTitleContributors: "[EMOJI] Conta",
  helpCommandDescriptionsContributor: "Somente para pessoas que partilharam a sua Wish Tally",
  helpCommandDescriptionRankWish: "Compara o seu número de 5-Estrelas com os da Comunidade",
  helpCommandDescriptionRank: "Exibe o rank médio dentro da Comunidade",
  helpCommandDescriptionPity: "Mostra a sua Piedade através do Pity Checker",
  helpCommandDescriptionAccount: "Menu de opções para contribuidores Wish Tally",
  helpCommandDescriptionRate: "Sumário de todas as vitórias e derrotas de todas as banners",



  // help-share Command
  helpShareEmoji: "🔓",
  helpShareCustomId: "[LOAD_HELP_SHARE]",
  helpShareName: "Partilhar a Wish Tally",
  helpShareTitle: "[EMOJI] Como partilhar a Wish Tally",

  helpShareMessageDescription: "Deve conectar-se ao servidor Discord da Wish Tally, para enviar o seu link de partilha.\n<[URL]>",
  helpShareMessage2Title: "Providenciar um Link de Partilha",
  helpShareMessage2Description: "Vá à barra de ferramentas, `Arquivo` e depois `Partilhar`",
  helpShareMessage3Title: "Editar Permissões",
  helpShareMessage3Description: "Altere as restrições de partilha clicando em `Alterar para qyakqyer pessoa com o link`",
  helpShareMessage4Title: "Qualquer pessoa com o link",
  helpShareMessage4Description: "Verifique que 3a está definido como `Visualizador`, pois o meu script apenas requer permissão para ver a planilha.\nClique em `Copiar Link` 3b para obter o link de partilha da sua Wish Tally sheet.\nPara confirmar as alterações clique em `Concluido` 3c",
  helpShareMessage5Title: "Mensagem direta ao ModMail",
  helpShareMessage5Description: "Envie o seu link de partilha ao BOT ModMail",
  helpShareMessage6Title: "Escolha ao Servidor do Discord",
  helpShareMessage6Description: "Indique ao ModMail que deseja enviar mensagem ao `Wish Tally - Genshin Impact Pity Tracker`. Clique no número correto....",
  helpShareMessage7Title: "Mensagem de confirmação",
  helpShareMessage7Description: "Deverá receber uma mensagem de confirmação pelo ModMail, a equipa irá entrar em contacto consigo a partir daí.",
  /*
   * help-addon Command
   */
  helpAddonEmoji: "📝",
  helpAddonCustomId: "[LOAD_HELP_ADDON]",
  helpAddonName: "Obter a Wish Tally",
  helpAddonTitle: "[EMOJI] Como obter a Wish Tally",
  helpAddonMessageDescription: "**Wish Tally é um Add-on Google Oficial**\nCom o Add-on aprovado pelo Google, este método tem que ser feito apenas **uma** vez, mesmo que crie várias planilhas novas. Não há uma grande mensagem de aviso pelo Google ao instalar este suplemento.\n\n__Visite este link para instalar o Add-on__\n<[URL]>\n\n",
  helpAddonMessage2Title: "Instalar o Add-On",
  helpAddonMessage2Description: "Siga a janela pop-up de permissão para instalar a Wish Tally",
  helpAddonMessage3Title: "Crie uma planilha Google em branco",
  helpAddonMessage3Description: "Após ter o add-on instalado, pode atribuí-lo à planilha. Crie uma nova planilha através de <[URL]> ou da barra de ferramentas `Arquivo` -> `Novo` -> `Planilha`",
  helpAddonMessage4Title: "Ativar o Add-on",
  helpAddonMessage4Description: "Para dar acesso total ao script, você tem que indicar ao Google para utilizar este add-on na planilha criada.\nVá a `Extensões` -> `Complementos` -> `Gerenciar Complementos`",
  helpAddonMessage5Title: "Ativar a Wish Tally",
  helpAddonMessage5Description: "Irá surgir uma janela após seleccionar gerenciar complementos. Clique nos 3 pontinhos e depois vá a `Usar neste documento` para ativar o add-on Wish Tally.",
  helpAddonMessage6Title: "Recarregue a sua Página",
  helpAddonMessage6Description: "**IMPORTANTE** - Recarregar o documento irá automaticamente alterar o local para `United Kingdom`, isto é necessário para as formulas da Wish Tally funcionarem.\n\nUtilize o botão de recarregar ou `F5` para forçar a página a atualizar.",
  helpAddonMessage7Title: "Inicie o Documento",
  helpAddonMessage7Description: "Use a barra de ferramentas `Complementos` -> `Wish Tally` -> `Initialise` para começar a carregar todas as páginas necessárias para a Wish Tally.",
  /*
   * help-import Command
   */
  helpImportEmoji: "📥",
  helpImportCustomId: "[LOAD_HELP_IMPORT]",
  helpImportName: "Importar Orações",
  helpImportTitle: "[EMOJI] Como Importar Orações",
  helpImportDescription: "Existe vários métodos de adicionar as suas oraçãos à Wish Tally, para evitar erro humano ao adicionar as orações deverá utilizar a `Auto Importação`.",
  helpImportDescriptionAutoTitle: "[EMOJI] Auto Importação (Recomendado)",
  helpImportDescriptionAuto: "Requer que entre no jogo e extraia o URL que se gere quando visita o Histórico de Orações.",
  helpImportDescriptionManualTitle: "[EMOJI] Importação Manual",
  helpImportDescriptionManual: "`Copiar` e `colar` as orações diretamente no documento, sem a necessidade de utilizar um API. Requer perceber como utilizar a coluna de override se não irá desordenar todas as orações, existem ferramentas disponíveis que ajudam a simplificar este método.",
  helpImportDescriptionExportTitle: "[EMOJI] Converter um Ficheiro de Exportação para a Wish Tally",
  helpImportDescriptionExport: "Se tiver um backup das suas orações de Wish Trackers alternativos, poderá usar um conversor de exportação.",
  /*
   * help-import-auto Command
   */
  helpImportAutoEmoji: "🖥️",
  helpImportAutoCustomId: "[LOAD_HELP_IMPORT_AUTO]",
  helpImportAutoName: "Auto Importação",
  helpImportAutoTitle: "[EMOJI] Auto Importar Orações",
  
  helpImportAutoMessageDescription: "Ajuda a importar automaticamente dados de orações para sua planilha Wish Tally usando a API miHoYo.\n\nIsto funciona utilizando o URL e extraindo a chave. Utilizando esta chave, a formula irá conectar-se por si ao miHoyo para verificar o seu histórico de orações e, se encontrar dados novas, o guardar na sua planilha Wish Tally. Não precisa de introduzir o override, uma vez que isso é feito automaticamente por si.\n\nPode utilizar na mesma o método de copiar e colar se desejar ser mais seguro, mas se preferir utilizar um método mais simples então siga os seguintes passos:\n**Note por favor que desejos antes dos últimos 6 meses não podem ser registados através deste método, tem que os registar antes que eles desapareçam do histórico.**",
  helpImportAutoMessage2Title: "PC Step 1 - Gerar o URL",
  helpImportAutoMessage2Description: "Entre no Genshin Impact, abra o menu de Orações e vá ao seu Histórico (não interessa de qual evento de oração). Isto irá criar um link no seu ficheiro log do Genshin.",
  helpImportAutoMessage3Title: "Step 2 - Encontrar o ficheiro log",
  helpImportAutoMessage3Description: "Abra o navegador de ficheiros no Windows e procure a pasta de instalação do jogo para encontrar o ficheiro `data_2` em \n`Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\Cache_Data\\`",
  helpImportAutoMessage4Title: "Step 3 - Extrair o URL",
  helpImportAutoMessage4Description: "Clique com o botão direito em `Abrir com` no ficheiro de texto `data_2` , escolha  `Bloco de Notas`",
  helpImportAutoMessage5Title: "Step 4 - Copiar o URL",
  helpImportAutoMessage5Description: "Perto do final do texto deste ficheiro encontrará um link a começar com:\n\n```https://hk4e-api-os.hoyoverse.com/............game_biz=h4e_global```\n\nSelecione e copie o link inteiro",
  helpImportAutoMessage6Title: "Step 5 - Começar a Auto Importação",
  helpImportAutoMessage6Description: "Certifique-se que a opção `Auto Import from miHoYo` está seleccionada na sua Wish Tally e clique no icon de importação para começar.",
  helpImportAutoMessage7Title: "Step 6",
  helpImportAutoMessage7Description: "Cole o URL na janela pop up da Auto Importação e de seguida pressione em `OK`.",
  helpImportAutoMessage8Title: "Para Servidores Chineses",
  helpImportAutoMessage8Description: "Altere o Servidor para `China` na página `Settings`, usando a setinha para baixo no B3 antes de começar a Auto Importação.",
  /*
   * help-import-manual Command
   */
  helpImportManualEmoji: "🖱️",
  helpImportManualCustomId: "[LOAD_HELP_IMPORT_MANUAL]",
  helpImportManualName: "Importação Manual",
  helpImportManualTitle: "[EMOJI] Importar manualmente as Orações",
  helpImportManualMessageDescription: "Na Wish Tally, você pode copiar e colar manualmente as suas orações como alternativa à Auto Importação. Este método não requer ferramentas adicionais, contudo é vital utilizar a coluna de override para orações múltiplas (com a mesma data e hora) de modo a garantir que as orações são registadas na ordem correta.",
  helpImportManualMessage2Title: "Passo 1 - Copira o Histórico para a Wish Tally",
  helpImportManualMessage2Description: "Vá ao menu de Orações e seleccione 'Histórico'.\n\nSeleccione a informação como demonstrado na imagem e copie-a utilizando o atalho `CTRL+C` (não é possível utilizar o botão direito do rato).",
  helpImportManualMessage3Title: "Passo 2",
  helpImportManualMessage3Description: "Através do `Dashboard`, vá à respetiva página de histórico na sua planilha.",
  helpImportManualMessage4Title: "Colar Valores",
  helpImportManualMessage4Description: "A aseguir, clique numa célula em branco da coluna A e depois use os atalhos `CTRL + V` ou `CTRL+ Shift + V` (Colar apenas Valores)",
  helpImportManualMessage5Title: "Problemas a Colar",
  helpImportManualMessage5Description: "Se os valores colados surgirem assim, você precisa de utilizar as opções de Colar através de clicar no botão direito do rato para evitar este problema ao colar.",
  helpImportManualMessage6Title: "Passo 3 - Utilizar a Override para gerir as orações múltiplas de 10 (Muito Importante)",
  helpImportManualMessage6Description: "Todas as orações múltiplas de 10 irão ter a mesma hora e data. Como o Histórico é apresentado do mais novo para o mais velho, temos que assumir a última entrada do múltiplo de 10 como desejo número 1.\n\nComece por copiar o histórico como demonstrado no passo anterior, depois numere esses itens na sua planilha usando este método.\n\nNo exemplo a seguir, o Raven bow no final da lista seria a primeira oração do múltiplo de 10",
  helpImportManualMessage7Title: "",
  helpImportManualMessage7Description: "Cole os valores [CTRL+V] e atribua o override manual introduzindo os números correspondentes.",
  helpImportManualMessage8Title: "",
  helpImportManualMessage8Description: "Siga para a próxima página (ex. vá para a Página 14 após copiar a 13) e faça o mesmo para as restantes orações múltiplas.",
  helpImportManualMessage9Title: "Passo 4 - Ordenar as Orações",
  helpImportManualMessage9Description: "Os valores têm que ser reordenados devido à ordem original do Histórico de Orações.\n\nCertifique-se que todas as orações múltiplas têm o seu número de override introduzido, se não tiver ao reordenar irá ficar tudo errado.\n\nClique no botão `SORT` no topo da página quando tiver tudo pronto.\n\nQuando clicar neste botão, o override irá automaticamente reordenar as orações múltiplas de 1 a 10 e orações únicas de acordo com a data e hora a que foram efectuadas.",
  /*
   * help-import-export Command
   */
  helpImportExportEmoji: "⛏️",
  helpImportExportCustomId: "[LOAD_HELP_IMPORT_EXPORT]",
  // List of options
  helpImportExportMessageOptionLayout: "\n[PROJECT_NAME] `[FILE_TYPE]`- <[URL]>",
  exportOption1ProjectName: "Exportar de Genshin Wish",
  exportOption1FileType: "XLSX file",
  exportOption1URL: "https://github.com/biuuu/genshin-wish-export",
  exportOption2ProjectName: "Genshin Wishes",
  exportOption2FileType: "CSV file",
  exportOption2URL: "https://genshin-wishes.com",
  exportOption3ProjectName: "paimon.moe",
  exportOption3FileType: "XLSX file",
  exportOption3URL: "https://paimon.moe",

  helpImportExportName: "Importar de Exportações",
  helpImportExportTitle: "[EMOJI] Importar Orações de outras Exportações",
  helpImportExportMessageDescription: "Use este conversor de documentos para ajudar a converter as suas orações para a Wish Tally.\n<[URL]>\n\n**Supported Export Files**",

  helpImportExportMessage2Title: "Criar uma cópia da planilha",
  helpImportExportMessage2Description: "Irá precisar de uma conta Google para aceder à planilha. Faça uma cópia da planilha para a sua Drive da Google.\n<[URL]>\n\nNa barra de ferramentas vá a `Arquivo`, clique em `Criar uma cópia`. Isto irá criar uma cópia da planilha na sua Drive, que depois poderá modificar para guardar o seu histórico.\n\nIrá surgir um popup para `Copiar o documento`, pode alterar o nome da planilha na secção `Nome`, clique em `OK` para guardar a sua cópia na sua Drive",
  helpImportExportMessage3Title: "Consulte o README",
  helpImportExportMessage3Description: "Para compreender melhor como usar o documento, por favor consulte a página `README`",
}