module.exports = {
  // List
  // https://emzi0767.gl-pages.emzi0767.dev/discord-emoji/discordEmojiMap-canary.json
  genshinVersions: {
    "1": {"1.0": {},"1.1": {},"1.2": {},"1.3": {},"1.4": {},"1.5": {},"1.6": {}},
    "2": {"2.0": {},"2.1": {},"2.2": {},"2.3": {},"2.4": {}, "2.5": {}, "2.6": {}, "2.7": {}, "2.8": {}},
    "3": {"3.0": {},"3.1": {},"3.2": {},"3.3": {},"3.4": {}, "3.5": {}, "3.6": {}, "3.7": {}, "3.8": {}},
  },
  genshinLatestVersions: {
    "version": "3.0", "image": "https://cdn.discordapp.com/attachments/814486266618970162/1012062259029229679/2022-08-24_combined_banner.png"
  },
  makerUserId:"358320066770501632",
  discordEmbedLengthLimit: 10,
  contentsName: "Contenidos", // Name of field
  contentsNameSelection: "\uD83D\uDD33",
  contentsNameDeselection: "▫️",

  displayAll: "Todos",
  displayNone: "Ninguno",
  displayTotal: "Total",
  displayGrandTotal: "Gran Total",
  displayAverageShorthand: "prom.",
  displayOtherItems: "Otros",
  displayBannerName: {
    "Character Event Banner": "Gachapón promocional de personaje",
    "Weapon Event Banner": "Gachapón promocional de arma",
    "Permanent Banner": "Gachapón permanente",
    "Novice Banner": "Gachapón de principiante",
  },
  displayWeaponType: {
    "Character": "Personaje",
    "Weapon": "Arma",
  },
  
  rarity5StarEmoji: "⋆⋆⋆⋆⋆",
  rarity5StarName: "5 Estrellas",
  rarity4StarEmoji: "⋆⋆⋆⋆",
  rarity4StarName: "4 Estrellas",
  rarity3StarEmoji: "⋆⋆⋆",
  rarity3StarName: "3 Estrellas",
  refreshName: "Recargar",
  refreshEmoji: "🔄",
  statusSuccessName: "Éxito",
  statusSuccessEmoji: "✅",
  statusErrorName: "Error",
  statusErrorEmoji: "❌",
  statusLoadingName: "Cargando",
  statusLoadingEmoji: "📂",
  statusCheckingName: "Revisando",
  statusCheckingEmoji: "⏳",
  statusProcessingName: "Procesando..",
  statusProcessingEmoji: "⏳",
  statusLoadedEmoji: "✅",
  statusLoadedName: "Cargado",
  statusLoadingEmoji: "⏳",
  statusLoadingName: "Está cargando",
  statusLoadEmoji: "❌",
  statusLoadName: "No cargado",

  urlImageError: "https://cdn.discordapp.com/attachments/814486266618970162/940599883658842122/error_1.png",
  urlImage5Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801560898850907/Final_5_Star.png",
  urlImage4Star: "https://cdn.discordapp.com/attachments/814486266618970162/940801559669923940/Final_4_Star.png",
  urlImageTally: "https://cdn.discordapp.com/attachments/814486266618970162/859426718754275399/Wish-Tally---Community.png",
  urlExportConvertor: "https://docs.google.com/spreadsheets/d/1lXGo_pKxKmTzd9pg1b1gr6Fa-zfcM2ZQd0EnFfzg8Dk/edit",
  urlDiscordInvite: "https://discord.gg/CKuJSbtndV",
  urlGoogleWishTallyAddon: "https://workspace.google.com/marketplace/app/wish_tally/791037722195",
  urlGoogleSheet: "https://docs.google.com/spreadsheets/u/0/",
  // output message
  replaceCodeURL: "[URL]",
  replaceCodeTitle: "[TITLE]",
  replaceCodeProjectName: "[PROJECT_NAME]",
  replaceCodeFileType: "[FILE_TYPE]",
  replaceCodeStatus: "[STATUS]",
  replaceCodeRank: "[RANK]",
  replaceCodeCommandName: "[COMMAND_NAME]",
  replaceCodeEmoji: "[EMOJI]",
  replaceCodeStatusEmoji: "[EMOJI_STATUS]",
  replaceCodeAccountId: "[ACCOUNT_ID]",
  replaceCodeAccountsMax: "[ACCOUNTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeCommandDescription: "[COMMAND_DESCRIPTION]",
  replaceCodeLanguage: "[LANGUAGE]",
  replaceCodeParameter: "[PARAMETER]",
  replaceCodeDate: "[DATE]",
  replaceCodeDocumentVersion: "[DOCUMENT_VERSION]",
  replaceCodeGenshinVersion: "[GENSHIN_VERSION]",
  replaceCodeAttemptIndex: "[ATTEMPTS_INDEX]",
  replaceCodeAttemptMax: "[ATTEMPTS_MAX]",
  replaceCodeUserId: "[USER_ID]",
  replaceCodeValue:"[VALUE]",
  replaceCodePercentage:"[PERCENTAGE]",
  outputContent: "[COMMAND_NAME]|[EMOJI_STATUS]|For <@[USER_ID]> |[LANGUAGE]|[PARAMETER]|[COMMAND_DESCRIPTION] [DATE]",

  latestVersionCustomId: "[LOAD_LATEST_VERSION]",
  latestVersionName: "Última Versión",
  latestVersionEmoji: "🔎",
  latestVersionTitle: "[EMOJI] Versión de Genshin Impact[GENSHIN_VERSION]",
  // ping Command
  replaceCodeBotName: "[BOT_NAME]",
  pingMessage: ":wave: [BOT_NAME] Sigo con vida",
  // last-update Command
  lastUpdateMessageError: "Por favor espera a que el cache cargue, estado: [STATUS]",
  lastUpdateMessageException: "Error, no se pudieron cargar los datos, estado: [STATUS]",
  lastUpdateName: "Última actualización",
  lastUpdateTitle: "Resumen de la Última Actualización del Documento de la Comunidad",
  lastUpdateEmoji: "⏲️",
  lastUpdateCustomId: "[LOAD_LAST_UPDATE]",
  lastUpdateDocumentTitle: "Community V[DOCUMENT_VERSION].X",

  lastUpdateStatusCommunityAccounts: "Documento de las Cuentas de la Comunidad",
  lastUpdateStatusLanguagePadding: 18,
  lastUpdateStatusDocumentPadding: 16,
  lastUpdateStatusDocument: "DOCUMENT LOADED",
  lastUpdateStatusDocumentAccount: "ACCOUNTS REFRESH",
  lastUpdateStatusDocumentCache: "CACHE REFRESH",
  lastUpdateStatusDocumentWishes: "BANNER REFRESH",
  lastUpdateStatusCommunityPadding: 15,
  lastUpdateStatusItemsByBanner: "ITEMS BY BANNER",
  lastUpdateStatusAccounts: "ACCOUNTS",
  lastUpdateStatusCharacterBannerPity: "PITY",
  lastUpdateStatusDatePadding: 5,
  lastUpdateStatusStartDate: "START",
  lastUpdateStatusEndDate: "END",
  lastUpdateStatusSummaryPadding: 14,
  lastUpdateStatusDuration: "DURATION",
  lastUpdateStatusAttempts: "ATTEMPTS",
  lastUpdateStatusMaxAccounts: "MAX ACCOUNTS",
  lastUpdateStatusTotalWishes: "TOTAL WISHES",
  lastUpdateStatusCurrentUpdates: "ACCOUNT CHECK",
  lastUpdateStatusHour: "hora",
  lastUpdateStatusHours: "horas",
  lastUpdateStatusAnd: "y",
  lastUpdateStatusMinute: "minuto",
  lastUpdateStatusMinutes: "minutos",
  lastUpdateStatusAgo: "antes",
  /*
   * account Command
   */
  accountEmoji: "🔑",
  accountCustomId: "[LOAD_ACCOUNT]",
  accountName: "Cuenta",
  accountTitle: "[EMOJI] Cuenta",
  accountDescriptionFound: "Gracias por contribuir a la Comunidad de Wish Tally, actualmente hay información de [ACCOUNTS_MAX] cuentas.\n\nAquí están las opciones exclusivas para ti.",
  accountDescriptionNotFound: "Disculpa que no podemos encontrar tu cuenta de Wish Tally, hay [ACCOUNTS_MAX] cuentas disponibles, pero ninguna ligada a tu Cuenta de Discord.\n\nPor favor visita la página de ayuda para aprender cómo contribuir a la Comunidad Wish Tally.\n\nSi recientemente has compartido tu Cuenta a ModMail, deberás esperar a que el staff revise tu documento.",
  accountDescriptionNotLoadedAccount: "El Bot recientemente ha limpiado el cache, pronto vovlerá a cargar las cuentas. Por el momento los botones se encuentras activos, pero este comando aún requiere ser ligado a tu cuenta de Wish Tally.",
  accountDescriptionLayout: "\n> [EMOJI][COMMAND_NAME] - [COMMAND_DESCRIPTION]",
  accountDescriptionRank: "Despliega tus deseos totales entre cada Documneto de la Comunidad, y muestra tu promedio del rango de pity (compasión).",
  accountDescriptionWish: "Despliega tu rango de contribución de deseos, útil para conocer qué versión de Genshin fue popular entre la comunidad.",
  accountDescriptionPity: "Extrae tu última pity (compasión) de tu documento, para mostrarle a otros tus deseos sin la necesidad de tomar una captura de pantalla.",
  accountDescriptionRate: "Muestra la tasa de victoria para los personajes limitados en `Banners de Personajes`.",
  /*
   * rank Command
   */
  rankEmoji: "🏆",
  rankCommunityEmoji: "🌎",
  rankCustomId: "[LOAD_RANK]",
  rankName: "Ranking",
  rankAccountTitle: "Resumen de Cuenta",
  rankTitle: "Resumen de Ranking",
  rankDescription: "El Ranking Personal es tu ranking utilizando los datos de tu documento de Wish Tally, El Ranking de la Comunidad considera el promedio de todas las cuentas, lo que significa que mientas menor el número, mayor la posición en el ranking.",
  rankCommunityTitle: "[EMOJI] Ranking de la Comunidad",
  rankPersonalTitle: "[EMOJI] Ranking Personal",
  rankNoWishes: "Ningún deseo realizado durante esta versión.",
  /*
   * rank-wish Command
   */
  rankWishEmoji: "✨",
  rankWishCustomId: "[LOAD_RANK_WISH]",
  rankWishName: "Deseos",
  rankWishLimit: 15,
  rankWishGenshinVersionLimit: 5,
  rankWishGenshinVersionSameLimit: 2,
  rankWishLimitPadding: 2,
  rankWishSameTotalLimit: 3,
  rankWishSameTotalMessage: "__Oculto [STATUS] Cuentas que tienen ranking [RANK]__",
  rankWishTitle: "Ranking de Deseos",
  rankWishNotReadyMessage: "La información de Deseos por cuentas no se han cargado, por favor intenta otra vez.\n[STATUS]",
  rankWishLoadedMessage: "Ranking de deseos se ha cargado exitosamente",
  rankWishYouEmoji: "👈",
  rankWishRarity4StarEmoji: "4⭐",
  rankWishRarity5StarEmoji: "5⭐",
  rankWishSelectVersionDefaultPlaceholderForAll: "Todos los Datos de la Comunidad",
  rankWishRankTitle: "Wish Tally Community V",
  rankWishRankGenshinTitle: "Genshin Version V",
  rankWishDocumentTitle: "Wish Tally Community V[DOCUMENT_VERSION].X",
  rankWishSelectVersionAllId: "[SELECT_RANK_WISH_VERSION_ALL]",
  rankWishSelectBannerIndexId: "[SELECT_RANK_WISH_BANNER_INDEX]",
  rankWishSelectVersionIndexId: "[SELECT_RANK_WISH_VERSION_INDEX]",
  rankWishMessageSuccessSelect: "Navegando entre banners",
  rankWishMessageError: "Se produjo un error, intente de nuevo más tarde",

  checkCommunityAccountMessageError: "Por favor espere a que la hoja de las Cuentas de la Comunidad cargue, estado: [STATUS]",
  // finding account only show for error
  findingAccountName: "Buscando Cuenta",
  findingAccountEmoji: "🔎",
  findingAccountMessageNotFound: "¡Error! No se pudo encontrar los detalles de tu cuenta de la Cuenta de la Comunidad\nSi ho te has unido a la comunidad, ve a la página de 'Help' para aprender como compartir tu Documento de Wish Tally, si lo hiciste recientemente, por favor espera a que la Comunidad se actualice.",
  findingAccountMessageException: "¡Error! No se pudo extraer información del Documento de la Comunidad [DOCUMENT_VERSION].",
  findingAccountMessageError: "Error, no se pudo encontrar la hoja de la Cuenta de la Comunidad",

  displayRankMessageError: "Error, no se pudo encontrar el Documento de la Comunidad [DOCUMENT_VERSION].",
  displayRankMessageNotFound: "El Documento de la Comunidad [DOCUMENT_VERSION], aún no tiene los detalles de tu cuenta. La posición de tu Cuenta es [ACCOUNT_ID] de [ACCOUNTS_MAX] cuentas disponibles, por favor espera a que la Comunidad se actualice.",
  displayRankMessageException: "¡Error! No se pudo extraer información de la Comunidad.",
  /*
   * pity Command
   */
  pityEmoji: "🧮",
  pityCustomId: "[LOAD_PITY]",
  pityName: "Compasión",
  pityMessageError: "Error al cargar tu documento",
  pityMessageLoading: "Cargando documento [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] intentos.",
  pityMessageUnableLoad: "Error, no se pudo cargar tu documento, intenta más tarde.",
  pityMessageUnableFind: "Error, no se pudo encontrar la hoja `Pity Checker` en tu documento.",
  pityMessageLoadingPity: "Cargando información de hoja `Pity Checker` [ATTEMPTS_INDEX]/[ATTEMPTS_MAX] intentos.",
  pityMessageUnablePityExtract: "Error, la extracción de la hoja de `Pity Checker` ha fallado totalmente, intenta más tarde.",
  pityMessagePitySheetOld: "La hoja 'Pity Checker' de tu documento no está actualizada, revisa <#836651770100842576>.",
  pityMessagePitySheetSuccess: "Desplegando la compasión desde tu documento",
  pityCurrentWishNumber: "Número de Deseo Actual",
  pityBackCustomId: "[LOAD_PITY_BACK]",
  pityNextCustomId: "[LOAD_PITY_NEXT]",
  pityBackEmoji: "⭐", // Back
  pityBackTitle: "⭐⭐⭐⭐⭐", // Back
  pityBackNoEarned: "⭐⭐⭐⭐⭐ - No se encontró 5 Estrellas", // Back
  pityBackName: "5 Estrellas", // Back
  pityNextEmoji: "⭐", // Next
  pityNextTitle: "⭐⭐⭐⭐", // Next
  pityNextNoEarned: "⭐⭐⭐⭐ - No se encontró 4 Estrellas", // Next
  pityNextName: "4 Estrellas", // Next
  /*
   * rate Command
   */
  rateEmoji: "🎯",
  rateCustomId: "[LOAD_RATE]",
  rateVersionCustomId: "[LOAD_RATE_VERSION]",
  rateName: "Promocionales",
  rateTitle: "[EMOJI] Promocionales",
  rateDescriptionSelection: "**Key**\n👎 - No se obtuvo el personaje promocional\n✌️ - Se ganó el 50/50\n👍 - Obtenido utilizando compasión anterior\n🙌 - Se uso compasión en el presente banner\n~~Elige qué versión de documento deseas ver en mayor detalle~~ Soon.",
  rateMessageError: "Se encontró un error al cargar la compasión del Banner de Personaje, intenta más tarde",
  rateNotReadyMessage: "Compasión del Banner de Personaje aún se está cargadno, por favor intenta más tarde.\n[STATUS]",
  rateLoadedMessage: "Resultados promocionales se han cargado exitosamente",
  rateMenuSelectDocumentVersionPlaceholder: "Selecciona Información de la Comunidad de Wish Tally",
  rateMenuSelectDocumentVersionCustomId: "[SELECT_RATE_MENU_VERSION]",
  rateMenuSelectDocumentVersionSelection: "Wish Tally Community V[DOCUMENT_VERSION].X",
  rateBannerDisplayLayout: "\n**Version [GENSHIN_VERSION]**",
  rateInnerBannerDisplayLayout: "\n__[TITLE]__",
  rateItemDisplayLayout: "\n> [TITLE]",
  rateFirstBanner: "Primer Banner",
  rateSecondBanner: "Segundo Banner",
  rateThirdBanner: "Tercer Banner",
  rateFourthBanner: "Cuarto Banner",
  rateFifthBanner: "Quinto Banner",
  rateEmptyTotal: "Ninguno obtenido",
  rateTotalTitle: "Total",
  rateResultLayout: "`[TITLE] [VALUE]`",
  rateTotalMaxPadding: 4,
  ratePercentageMaxPadding: 3,
  rateWinEmoji: "✅",
  rateWinName: "", // Not in use
  rateLoseEmoji: "❌",
  rateLoseName: "", // Not in use

  rateFailedToGetEmoji: "👎",
  rateFailedToGetName: "Fracaso",
  rateFailedToGetDetailed: "No se pudo obtener personajes promocionales",
  rateWonFiftyFiftyEmoji:"✌️",
  rateWonFiftyFiftyName:"Ganar 50/50",
  rateWonFiftyFiftyDetailed:"Se ganó el 50/50",
  rateUsedPityEmoji: "👍",
  rateUsedPityName: "Compasión utilizada",
  rateUsedPityDetailed: "Ganado utilizando compasión previa",
  rateSkippedEmoji: "👉", // Not in use
  rateSkippedName: "Saltado", // Not in use
  rateSkippedDetailed: "Sin Intentos de 5-Estrellas",
  rateSecondAttemptEmoji: "🙌",
  rateSecondAttemptName: "Se utilizó la compasión actual",
  rateSecondAttemptDetailed: "Se utilizó la compasión en el banner actual",
  rateResultLeftPercentageLayout: "[EMOJI]`[VALUE]|[PERCENTAGE]%`",
  rateResultCenterPercentageLayout: "▰",
  rateResultRightPercentageLayout: "`%[PERCENTAGE]|[VALUE]`[EMOJI]",
  rateResultPercentageCovered: "▰",
  rateResultPercentageUncovered: "▱",

  languageSelectByNameCustomId: "[SELECT_LANGUAGE_NAME]",
  /*
   * tally Command
   */
  tallyEmoji: "\uD83E\uDEA7",
  tallyCustomId: "[LOAD_TALLY]",
  botEmoji: "<:wish_tally:1015215165500825611>",
  tallyName: "Menú",
  tallyTitle: "[EMOJI] Wish Tally Bot",
  tallyDescription: "**[EMOJI] Bienvenido al Menú de Wish Tally**\n__Bot es administrado por <@[USER_ID]>__",
  tallyDescriptionBot: "Utiliza los botones siguientes para controlar el [EMOJI] Wish Tally bot.",
  tallyDescriptionHelp: "Únicamente datos de la Comunidad Wish Tally Community son mostrados aquí, revisa la [EMOJI] Página de Ayuda para agregarte. \n\n**Por favor considera** que __únicamente la persona que solicitó el bot puese controlar el bot__.",
  /*
   * report-m[DOCUMENT VERSION] Back Command
   */
  reportDocumentEmoji: "\uD83D\uDCD4",
  reportDocumentCustomId: "[LOAD_COMMUNITY_VERSION]",
  reportDocumentName: "Documento",
  /*
   * report-m Command Load all doc
   */
  reportMenuEmoji: "<:wish_tally_community:1015216582231871611>",
  reportMenuCustomId: "[LOAD_COMMUNITY]",
  reportMenuName: "Comunidad",
  reportMenuResetCustomId: "[LOAD_COMMUNITY_RESET]",
  reportMenuResetEmoji: "🗑️",
  reportMenuResetName: "Reiniciar Filtro",
  reportMenuMessageError: "No se pudo cargar el Documento de la Comunidad para la Versión `[DOCUMENT_VERSION]` podría no existir aún?",
  reportMenuMessageErrorLoading: "Documento de la Comunidad para la Versión `[DOCUMENT_VERSION]` no se ha cargado aún.",
  reportMenuMessageException: "Error encontrado, no se pudo cargar el reporte del Documento de la Comunidad Versión `[DOCUMENT_VERSION]`, por favor intenta una vez más?",
  reportMenuMessageNoData: "No se encontró información que desplegar para Documento de la Comunidad Versión `[DOCUMENT_VERSION]`, por favor intenta una vez más?",
  reportMenuMessageFound: "Desplegando Documento de la Comunidad Versión `[DOCUMENT_VERSION]`",
  reportMenuDefaultPlaceholderForAll: "Toda la Información de la Comunidad",
  reportMenuSelectCustomId: "[SELECT_REPORT_MENU_VERSION]",
  reportMenuSelectAllId: "[SELECT_REPORT_MENU_ALL]",
  reportMenuSelectGensionVersionCustomId: "[SELECT_GENSHIN_VERSION]",
  reportMenuSelectGenshinVersionPlaceholder: "Seleccionar Versión de Genshin Impact",
  reportMenuSelectGensionVersionName: "Genshin Impact V[GENSHIN_VERSION]",
  reportMenuSelectIndexCustomId: "[SELECT_REPORT_MENU_INDEX]",
  reportMenuDocumentTitle: "Wish Tally Community V[DOCUMENT_VERSION].X",
  reportMenuDocumentSelectionTitle: "Wish Tally Community V[DOCUMENT_VERSION]", // Wish Tally Community V2.0 - 2.6
  reportMenuMessageSuccess: "Desplegando menú de reporte",
  /*
   * Select Menu default error message, will display refresh name and emoji for [COMMAND_DESCRIPTION]
   */
  selectMenuMessageCacheError: "No se pueden hacer cambios entre mensajes, resume el último mensaje o utiliza [COMMAND_DESCRIPTION].",
  selectMenuMessageCacheRestarted: "El Bot ha reiniciado, no se pueden mover las páginas, utiliza [COMMAND_DESCRIPTION].",
  /*
   * report-v[GENSHIN_VERSION] Command
   * Show specific Genshin Version, with all banners
   */
  reportEmoji: "\uD83D\uDCD4",
  reportCustomId: "[LOAD_REPORT_VERSION]",
  reportName: "Reporte",
  reportMessageError: "No se pudo cargar el Documento de la Comunidad para la Versión [GENSHIN_VERSION] en el documento 'v[DOCUMENT_VERSION]' podría no existir aún?",
  reportMessageException: "Cargado el documento v[DOCUMENT_VERSION], pero la versión [GENSHIN_VERSION] ha encontrado un error, por favor intenta una vez más",
  reportMessageUnableFindVersion: "Cargado el documento v[DOCUMENT_VERSION], pero la versiónn [GENSHIN_VERSION] parece no existir aún, por favor intenta más tarde",
  reportMessageNoWishes: "Cargado el documento v[DOCUMENT_VERSION], se encontró la versión [GENSHIN_VERSION] pero no hay deseos disponibles, por favor intenta más tarde",
  reportMessageFound: "Cargada información para versión [GENSHIN_VERSION]",
  reportSelectCustomId: "[SELECT_REPORT_VERSION]",
  reportSelectIndexCustomId: "[SELECT_REPORT_INDEX]",
  reportMessageSuccess: "Desplegando reporte",
  /*
   * help Command
   * Homepage for help, will show all the steps
   */
  helpEmoji: "❓",
  helpCustomId: "[LOAD_HELP]",
  helpName: "Ayuda",
  helpTitle: "[EMOJI] Página de Ayuda",
  googleAddonEmoji: "",
  googleAddonName: "Extensión de Google",
  discordServerEmoji: "",
  discordServerName: "Unirse al Servidor",
  helpStepsDescriptionLayout: "\n> [EMOJI][TITLE]",
  helpDescription: "Utilizando las reacciones siguientes, carga la ayuda relevante.\n\nWish Tally es una extensión de Google utilizada para mantener la cuenta de los deseos, es necesaria para compartir a la Comunidad de Wish Tally.",
  helpStep1Title: "Paso 1 - [EMOJI]",
  helpStep1Description: "Cómo obtener Wish Tally",
  helpStep2Title: "Paso 2 - [EMOJI]",
  helpStep2Description: "Cómo importar Deseos",
  helpStep3Title: "Paso 3 - [EMOJI]",
  helpStep3Description: "Cómo compartir a Wish Tally",
  helpCommandDescription: "Acceso directo para desplegar información sin navegar desde la [EMOJI] Lista de Comandos",
  /*
   * help-command Command
   * List all the bot commands, useful for directly going to a specific page
   */
  helpCommandEmoji: "⌨️",
  helpCommandName: "Comandos",
  helpCommandTitle: "[EMOJI] Lista de Comandos",
  helpCommandCustomId: "[LOAD_HELP_COMMAND]",
  helpCommandDescription: "Acceso Directo navegando con comandos",
  helpCommandDescriptionTally: "Muestra el menú principal",

  helpCommandMessageDisplay: "\n`[COMMAND_NAME]`\n> [COMMAND_DESCRIPTION]",

  helpCommandTitleHelp: "[EMOJI] Sección de Ayuda",
  helpCommandDescriptionHelp: "Menú de Ayuda",
  helpCommandDescriptionHelpAddon: "Obtén el Complemento de Wish Tally",
  helpCommandDescriptionHelpImport: "Opciones de Importación",
  helpCommandDescriptionHelpImportAuto: "Auto Importador",
  helpCommandDescriptionHelpImportManual: "Manual",
  helpCommandDescriptionHelpImportExport: "Exportar",
  helpCommandDescriptionHelpShare: "Comparte el Wish Tally",

  helpCommandTitleBotStat: "[EMOJI] Información del Bot",
  helpCommandDescriptionHelpLastUpdate: "Despliega última actualización para cargar información de la Comunidad, de acuerdo a lo agendado",

  helpCommandTitleData: "[EMOJI] Sección de Datos",
  helpCommandDescriptionReportMenu: "Despliega un resumen de todo el documento de la comunidad",
  helpCommandDescriptionReportMenuSelection: "Selecciona un documento específico para el reporte, ejemplo `!wish report-m2` para el documento de la comunidad v2.X",
  helpCommandDescriptionReport: "Genera un reporte para una versión específica de Genshin Impact, ejemplo `!wish report-v2.4`",

  helpCommandTitleContributors: "[EMOJI] Cuenta",
  helpCommandDescriptionsContributor: "Únicamente para personas que han compartido su Wish Tally",
  helpCommandDescriptionRankWish: "Compara tu número de 5-Estrellas con la comunidad",
  helpCommandDescriptionRank: "Despliega tu ranking promedio dentro de la Comunidad",
  helpCommandDescriptionPity: "Muestra tu compasión desde el Pity Checker",
  helpCommandDescriptionAccount: "Opciones de Menú para contribuyentes de Wish Tally",
  helpCommandDescriptionRate: "Sumario de todos los éxitos en la obtención de ítems destacados en los banners",



  // help-share Command
  helpShareEmoji: "🔓",
  helpShareCustomId: "[LOAD_HELP_SHARE]",
  helpShareName: "Comparte Wish Tally",
  helpShareTitle: "[EMOJI] Cómo compartir Wish Tally",

  helpShareMessageDescription: "Debes unirte al servidor de Discord de Wish Tally, para enviar un mensaje con tu liga para compartir.\n<[URL]>",
  helpShareMessage2Title: "Proveyendo una Liga para Compartir",
  helpShareMessage2Description: "Dirígente a la barra de tareas, `Archivo` y posteriormente `Compartir`",
  helpShareMessage3Title: "Cambiar las restricciones de compartir",
  helpShareMessage3Description: "`Cambiar` las restricciones para que cualquier usuario de internet con este enlace lo pueda ver",
  helpShareMessage4Title: "Cualquier persona con el enlace",
  helpShareMessage4Description: "Revisa que 3b aparezca en `Lector`, ya que mi script únicamente necesita permiso para ver la hoja.\nDa click en `Copiar enlace` 3c para proveerme con el enlace de tu hoja de Wish Tally.\nPara confirmar los cambios da click en `Hecho` 3d",
  helpShareMessage5Title: "Envía un mensaje directo a ModMail",
  helpShareMessage5Description: "Envía tu liga para compartir al BOT ModMail",
  helpShareMessage6Title: "Elige el servidor de Discord",
  helpShareMessage6Description: "Informa a ModMail que deseas enviar el mensaje a `Wish Tally - Genshin Impact Pity Tracker`. Da click en el número correcto....",
  helpShareMessage7Title: "Confirmación del mensaje",
  helpShareMessage7Description: "Deberás recibir un mensaje de conformación de ModMail, el staff te apoyará a partir de ese punto.",
  /*
   * help-addon Command
   */
  helpAddonEmoji: "📝",
  helpAddonCustomId: "[LOAD_HELP_ADDON]",
  helpAddonName: "Obten Wish Tally",
  helpAddonTitle: "[EMOJI] Cómo obtener Wish Tally",
  helpAddonMessageDescription: "**Wish Tally es un Complemento Oficial Google**\nCon el Complemento aprobado por Google, este método únicamente será requerido **una vez**, aún elaborando hojas múltiples. Además, no hay mensaje de advertencia por parte de Google al instalar este Complemento.\n\n__Visita aquí para instalar el Complemento__\n<[URL]>\n\n",
  helpAddonMessage2Title: "Instalar el Complemento",
  helpAddonMessage2Description: "Acepta las ventanas emergentes para instalar Wish Tally",
  helpAddonMessage3Title: "Crea una hoja de cálculo en blanco",
  helpAddonMessage3Description: "Una vez instalado el complemento, lo puedes asignar a cualquier hoja de cálculo. Simplemente crea una hoja de cálculo desde <[URL]> o en la barra de tareas `Archivo` -> `Nuevo` -> `Hoja de cálculo`",
  helpAddonMessage4Title: "Habilitando el Complemento",
  helpAddonMessage4Description: "Para otorgarle acceso al script, deberás solicitarle a Google que utilice el complemento en esta nueva hoja de cálculo.\nDirígete a `Extensiones` -> `Complementos` -> `Gestionar complementos`",
  helpAddonMessage5Title: "Habilitando Wish Tally",
  helpAddonMessage5Description: "Una ventana emergente aparecerá después de seleccionar getionar complementos. Dirígente a los 3 puntos y selecciona `Unsar en este documento` para habilitar el complemento de Wish Tally.",
  helpAddonMessage6Title: "Refresca la página",
  helpAddonMessage6Description: "**IMPORTANTE** - Refrescar el documento cambiará automáticamente la ubicación a `Reino Unido`, lo que le permitirá a las fórmulas funcionar adecuadamente.\n\nUsa el botón de volver a cargar página de tu explorador o `F5` para forzar a la página a refrescarse.",
  helpAddonMessage7Title: "Iniciar el Documento",
  helpAddonMessage7Description: "Desde barra de tareas: `Extensiones` -> `Wish Tally` -> `Initialise` para comenzar a cargar todas las hojas requeridas por Wish Tally.",
  /*
   * help-import Command
   */
  helpImportEmoji: "📥",
  helpImportCustomId: "[LOAD_HELP_IMPORT]",
  helpImportName: "Importar Deseos",
  helpImportTitle: "[EMOJI] Cómo Importar Deseos",
  helpImportDescription: "Hay múltiples métodos para agregar deseos al documento de Wish Tally, para evitar errores humanos a la hora de introducir deseos, se puede utilizar el `Auto Import`.",
  helpImportDescriptionAutoTitle: "[EMOJI] Auto Import (Recomendado)",
  helpImportDescriptionAuto: "Requiere iniciar sesión en el juego y extraer la URL cuando se revise el Historial de Deseos.",
  helpImportDescriptionManualTitle: "[EMOJI] Importación Manual",
  helpImportDescriptionManual: "Sencillamente `copia` y `pega` los deseos directamente, sin la necesidad de utilizar la API. Deberás entender cómo utilizar la columna de sobre-escribir, de lo contrario, los deseos apareceran desordenados, existen herramientas disponibles que ayudan a simplificar este método.",
  helpImportDescriptionExportTitle: "[EMOJI] Convertir archivos de esportación a Wish Tally",
  helpImportDescriptionExport: "Si tienes respladados tus deseos en gestores de deseos alternativos, puedes utilizar un convertidor para exportar.",
  /*
   * help-import-auto Command
   */
  helpImportAutoEmoji: "🖥️",
  helpImportAutoCustomId: "[LOAD_HELP_IMPORT_AUTO]",
  helpImportAutoName: "Auto Import",
  helpImportAutoTitle: "[EMOJI] Auto Importar Deseos",
  
  helpImportAutoMessageDescription: "Esto es para ayudar a importar tu información de deseos automáticamente a tu hoja de Wish utilizando la API de miHoYo.\n\nEsto funciona utilizando la URL y extrayendo la llave. Con la llave se comunicará directamente con miHoYo para revisar el historial de deseos, y almacenando los deseos nuevos en tu hoja deWish Tally. No tendrás que sobre-escribir manualmente, ya que esto se realiza automáticamente.\n\nAún podrás utilizar el método de copiar y pegar como una manera más segura de salvar tu historial de deseos, pero si deseas utilizar esta opción más simple, puedes seguir los siguientes pasos:\n**Por favor considera que cualquier Deseo anterior a 6 meses no podrá ser obtenido de esta manera, deberás salvarlos antes de que desaparezcan.**",
  helpImportAutoMessage2Title: "PC Paso 1 - Genera la URL",
  helpImportAutoMessage2Description: "Inicia sesión en Genshin Impact, abre el menú de Gachapón y visita la página del historial (no importa el historial del banner que abras). Esto generará una URL en el archivo de texto de registro de Genshin Impact.",
  helpImportAutoMessage3Title: "Paso 2 - Encontrando el Archivo de registro",
  helpImportAutoMessage3Description: "Abre el explorador de archivos en Windows, encuentra la carpeta de instalación de tu juego, y encuentra el archivo `data_2` en la ruta: \n`Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\Cache_Data\\`",
  helpImportAutoMessage4Title: "Paso 3 - Extrae la URL",
  helpImportAutoMessage4Description: "Da click derecho en el archivo de texto `data_2`, selecciona `Abrir como` y elige `Bloc de notas`",
  helpImportAutoMessage5Title: "Paso 4 - Copia la URL",
  helpImportAutoMessage5Description: "Cerca del fin del texto encontrarás una dirección que comienza con:\n\n```https://hk4e-api-os.hoyoverse.com/............game_biz=h4e_global```\n\nSelecciónala toda y cópiala",
  helpImportAutoMessage6Title: "Paso 5 - Comenzando Auto Import",
  helpImportAutoMessage6Description: "Asegúrate que la opción de importación se encuentra seleccionada en `Auto Import from miHoYo` y da click en el ícono de importar para comenzar.",
  helpImportAutoMessage7Title: "Paso 6",
  helpImportAutoMessage7Description: "Pega la URL en la ventana emergente del Auto Import, y presiona `OK`.",
  helpImportAutoMessage8Title: "Para Servidores de China",
  helpImportAutoMessage8Description: "Cambia el servidor a `China` en la hoja de `Settings`, utilizando la opción que se muestra en B3. Antes de comenzar a utilizar el Auto Import.",
  /*
   * help-import-manual Command
   */
  helpImportManualEmoji: "🖱️",
  helpImportManualCustomId: "[LOAD_HELP_IMPORT_MANUAL]",
  helpImportManualName: "Importación Manual",
  helpImportManualTitle: "[EMOJI] Importando Deseos Manualmente",
  helpImportManualMessageDescription: "En Wish Tally puedes copiar y pegar manualmente tu historial como una alternativa al método de auto importación. Este método funciona sin el uso de herramientas externas, sin embargo, es importante utilizar la columna de sobreescritura para los tiros de 10 deseos (con la misma fecha y hora), con el fin de que los deseos se registren en el orden correcto.",
  helpImportManualMessage2Title: "Paso 1 - Copiar el historial de deseos",
  helpImportManualMessage2Description: "Ve al menú de 'Gachapón' y selecciona 'Historial'.\n\nCon el cursor, selecciona/resalta la información como se muestra en la imagen, y cópiala usando las teclas CTRL+C (la opción de copiar con el botón derecho del mouse está deshabilitada).",
  helpImportManualMessage3Title: "Paso 2",
  helpImportManualMessage3Description: "Desde el panel de control, o 'Dashboard', dirígete a la pestaña respectiva del historial que copiaste.",
  helpImportManualMessage4Title: "Pegando valores",
  helpImportManualMessage4Description: "Next, press an empty cell in column A, and press `CTRL + V` or `CTRL+ Shift + V` (Paste Values Only)",
  helpImportManualMessage5Title: "Problemas al Pegar",
  helpImportManualMessage5Description: "Si la información, al pegarla, se ve como en la imagen de la izquierda, deberás evitar utilizar la opción de botón derecho -> Pegado especial -> Solo valores.",
  helpImportManualMessage6Title: "Paso 3 - Gestionando tiros de 10 deseos utilizando sobreescritura (Muy importante).",
  helpImportManualMessage6Description: "Todos los tiros multi de 10 tendrán el mismo registro de fecha y hora. Sin embargo, como el historial en Genshin es desplegado del tiro más nuevo al más viejo, podemos asumir que la última entrada en un tiro multi de 10 es el deseo número 1.\n\nPrimero, copia el historial usando el método mostrado anteriormente, depués, numera estos ítems en tu hoja de cálculo ordenándolos del más nuevo al más viejo.\n\nEn el ejemplo siguiente, el arma 'Raven Bow' al final de la lista sería el primer ítem obtenido. Notar como los 5 ítems numerados presentan la misma fecha y hora de obtención.",
  helpImportManualMessage7Title: "",
  helpImportManualMessage7Description: "Pega los valores y asigna manualmente los números de obtención de los ítems en la columna de 'Override' (Sobreescritura).",
  helpImportManualMessage8Title: "",
  helpImportManualMessage8Description: "Continúa en la siguiente página (en este ejemplo de la 14 a la 13) y haz lo mismo con el resto del tiro multi de 10.",
  helpImportManualMessage9Title: "Paso 4 - Ordenar los Deseos",
  helpImportManualMessage9Description: "Debido a la incongruencia entre los listados del historial de Genshin y la hoja de cálculo, los valores pegados deberán ser ordenados.\n\nAsegúrate que todos los tiros multi cuenten con su numeración sobreescita, de lo contrario, el orden quedará mal.\n\nPresiona el botón `SORT` (ordenar) que se encuentra en la parte superior de la lista.\n\nCuando la función ordenar es aplicada, la sobreescritura automáticamente ordenará los tiros multi de 1 a 10, así como los individuales, en orden de fecha y hora.",
  /*
   * help-import-export Command
   */
  helpImportExportEmoji: "⛏️",
  helpImportExportCustomId: "[LOAD_HELP_IMPORT_EXPORT]",
  // List of options
  helpImportExportMessageOptionLayout: "\n[PROJECT_NAME] `[FILE_TYPE]`- <[URL]>",
  exportOption1ProjectName: "Exportación de Deseos de Genshin",
  exportOption1FileType: "XLSX file",
  exportOption1URL: "https://github.com/biuuu/genshin-wish-export",
  exportOption2ProjectName: "Deseos de Genshin",
  exportOption2FileType: "CSV file",
  exportOption2URL: "https://genshin-wishes.com",
  exportOption3ProjectName: "paimon.moe",
  exportOption3FileType: "XLSX file",
  exportOption3URL: "https://paimon.moe",

  helpImportExportName: "Exportar Importar",
  helpImportExportTitle: "[EMOJI] Importar Deseos desde la Exportación",
  helpImportExportMessageDescription: "Utiliza este documento convertidor para ayudar a convertir tus deseos a Wish Tally.\n<[URL]>\n\n**Archivos de Exportación Soportados**",

  helpImportExportMessage2Title: "Realiza una copia de la hoja de cálculo",
  helpImportExportMessage2Description: "Deberás tener una cuenta de Google antes de poder acceder a la hoja de cálculo. Realiza una copia de esta hoja de cálculo en tu Google Drive.\n<[URL]>\n\nEn el menú `Archivo` de la barra de tareas, da click en `Hacer una copia`.Esto creará una copia de la hoja de cálculo master en tu Google Drive, la cual podrás modificar para almacenar tu historial de deseos.\n\nAparecerá una ventana emergente, en ella podrás renombrar el documento en el espacio de `Nombre`, posteriormente da click en `Aceptar` para salvar la copia del Wish Tally en tu Google Drive.",
  helpImportExportMessage3Title: "Revisa el README",
  helpImportExportMessage3Description: "Para entender mejor cómo utilizar el convertidor de documentos, por favor revisa la hoja de `README`",
}